### ISSUE TITLE
utilities.apiclient: Payload gets lost in put request

### ISSUE THREAD

**Issue by merretbuurman** [rapydo/issues#102]
Hi,
I noticed that when I use the apiclient to make a PUT request, my JSON payload gets lost, unless I explicitly call json.dumps on it before passing it:

Fails (also, it exits upon receiving a http 400, even though I explicitly ask not to):
```
response = apiclient.call(
	uri,
	endpoint=qc_endpoint, token=token, method='put',
	payload=payload, exit_on_fail=False)
```

Output (the missing request_id is present in the JSON payload, and when I use the requests library, so the call works fine):
```
2018-05-28 18:55:53,859 [VERY_VERBOSE utilities.apiclient:107] Calling put on /api/ingestion/foo/qc/bar
2018-05-28 18:55:54,127 [VERY_VERBOSE utilities.apiclient:151] URL: https://foo.cineca.it/api/ingestion/foo/qc/bar
<Response [400]>
2018-05-28 18:55:54,193 [CRITICAL utilities.apiclient:68] API request failed (or not completed)
2018-05-28 18:55:54,193 [ERROR   utilities.apiclient:77] Missing JSON key: request_id
```

Works (using requests):
```
import requests
resp = requests.put(
    uri+qc_endpoint, headers=headers, json=payload)
```

Works (using apiclient):
```
import json
response = apiclient.call(
	uri,
	endpoint=qc_endpoint, token=token, method='put',
	payload=json.dumps(payload), exit_on_fail=False)
```

I noticed that in the apiclient, in line 105, the payload is json-dumped for POST and for PATCH, but not for PUT, so if there is no particular reason for excluding PUT, including PUT there would solve the issue.

**Comment by pdonorio** [comment]
> so if there is no particular reason for excluding PUT

Thanks for the catch!
It was excluding `PUT` because the apiclient was written specifically for the EUDAT HTTP API, which use that method for streaming the upload, so there must be no JSON in the content.

I've pushed a "possible" fix above, you can test it reinstalling the latest utils like that:
```
pip3 install --upgrade git+https://github.com/rapydo/utils.git@0.6.2
```

**Comment by pdonorio** [comment]
@merretbuurman can you tell if the bug is fixed?

**Comment by pdonorio** [comment]
Feel free to re-open if needed
