### ISSUE TITLE
Merge backend and celery builds

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#104]
These two builds are quite similar and we could merge them to simplify the management and avoid duplication

Also considering the split between backend and backend-irods (and in a future the introduction of a backend-alpine) we should now create celery, celery-irods and celery-alpine (duplication issues x3)

After a check the difference between such images are:

- Dockerfile: different commands echoed in /usr/bin (restapi for backend, mycelery and myflower for celery) (easy to merge)
- Dockerfile: different CMD ("docker-entrypoint", "rest" for backend and mycelery for celery) (ovveride CMD from backend.yaml?)
- Dockerfile: different ENTRYPOINT ("/usr/bin/dumb-init", "--", "rest" for backend and "docker-entrypoint"for celery) (ovverride entrypoint from backend.yaml?)
- several differences in docker-entrypoint.sh (add two different entrypoint scripts?)

- 1 more lib in celery/requirements (flower) (easy to add)

**Comment by pdonorio** [comment]
Looks easy. It should be done.

**Comment by mdantonio** [comment]
It is done, let's test it

**Comment by mdantonio** [comment]
It works.

Note: now celery build is deprecated (templates_builds/celery_deprecated) and will be removed in a near future
