### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#105]
We should have more often rapydo releases.

Let's plan `0.6.2` at the end of the month, then after the summer stop (August) I'd hope to have one release per month.

**Comment by pdonorio** [comment]
Ready to release 0.6.2!

**Comment by pdonorio** [comment]
Maybe tomorrow XD

**Comment by pdonorio** [comment]
We can try again today, but there is a security warning in `tests` repo:
https://www.dropbox.com/s/mkqr61eysrs189o/Screenshot%202018-07-30%2011.48.39.png?dl=0

@mdantonio could we fix it?

**Comment by mdantonio** [comment]
the security warning is about a javascript library used by the angularJS code... To be honest at the moment we do not want to make any update on the angularJS code

**Comment by pdonorio** [comment]
End of september, let's book 24-28 week!

**Comment by mdantonio** [comment]
Future releases will be announced on slack

> End of september, let's book 24-28 week!
Added the reminder on slack

This issue can be closed
