### ISSUE TITLE
Service option in templating

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#106]
This should be an easy one...

We need to allow the rapydo user to specify which service they intend to use when templating a new endpoint, e.g.

`rapydo --service mongo template mynewendpoint` to avoid using sqlalchemy.

Also: would that be possible to be guessed automatically? 🤔

**Comment by mdantonio** [comment]
Little interest for me, to be honest I do not use templating... but I agree that the option should be simple to be added

> Also: would that be possible to be guessed automatically? 
Yes, a loop against detect to inject all available services could be useful

**Comment by pdonorio** [comment]
It's actually difficult to check if a service requested exists because that part exists only in the `http-api` repo, not in `controller`.

But at least now I choose the auth service as the default.
