### ISSUE TITLE
Convert roles in profile into a list instead of hashmap

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#108]
Currently the list of roles provided from the `/auth/profile` endpoint respond with a `dict` for the roles list. It should be a `list` instead.

**Comment by pdonorio** [comment]
Here's where we are creating the dictionary:
https://github.com/rapydo/http-api/blob/0.6.2/restapi/resources/endpoints.py#L527-L530

It seems it is not used for authentication because that happens here:
https://github.com/rapydo/http-api/blob/0.6.2/restapi/services/authentication/__init__.py#L454-L477

@mdantonio could you let me know if I can push this change asap?

**Comment by mdantonio** [comment]
We could change this, but than we will also have to fix both AngularJS and Angular web interfaces otherwise roles checks will be broken

**Comment by pdonorio** [comment]
Ok, so I'll wait for you to do it. The backend modifications is quite simple, I have no idea for angular/angularjs. I can take the effort for angularjs if you show me where ;)

**Comment by pdonorio** [comment]
Will try tonight

**Comment by pdonorio** [comment]
Pushed in 0.6.3, check and close

**Comment by mdantonio** [comment]
Fixed on Angular and verified on AngularJS, we can close
