### ISSUE TITLE
Do unittests

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#11]
We need to add unittests for the do command.

The mechanism behind this component of the project is very different from the HTTP API server, so we could use it to try new ways.

Ideas:

- use `pytest`
- integrate `tox` with `travis.ci` (e.g. like [this](https://tox-travis.readthedocs.io/en/stable/)). This is related to #10

**Comment by pdonorio** [comment]
An example of how to combine travis and tox is given by how the `pip` command is coded.

See the [tox.ini](https://github.com/pypa/pip/blob/master/tox.ini) made by them and the related [matrix for travis](https://github.com/pypa/pip/blob/master/.travis.yml#L4-L27)

**Comment by mdantonio** [comment]
We implemented a set of test (with pytest) for do on issue #38 

We also implemented unittest for utilities

And we are working on unitest for restapi in #37 

=> This issue can be closed
