### ISSUE TITLE
Generic meta customizer class

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#112]
We often have the need to customize part of things already implemented in rapydo.

One common pattern I saw is to have a class that customize a subpart of a base implemented class.
One example here is the `Initializer`.
Since I need to customize part of the Profile endpoint I came up with the idea of refactoring the code for the meta import of the `Initializer` to be used "world wide" in rapydo :)

**Comment by mdantonio** [comment]
Once completed i could remove the following custom part in endpoints:
```

        if hasattr(current_user, 'irods_user'):
            data["irods_user"] = current_user.irods_user
            if not data["irods_user"]:
                data["irods_user"] = None
            elif data["irods_user"] == '':
                data["irods_user"] = None
            elif data["irods_user"] == '0':
                data["irods_user"] = None
            elif data["irods_user"][0] == '-':
                data["irods_user"] = None
```

Just let me know where i should move that piece of code

**Comment by pdonorio** [comment]
You need to create a `projects/YOURPROJECT/backend/apis/profile.py` file with a content looking like:

```# -*- coding: utf-8 -*-

from utilities.logs import get_logger
from MYPROJECT.apis import SERVICE_NAME, compute

log = get_logger(__name__)


class CustomProfile(object):

    def manipulate(self, ref, user, data):

        cname = self.__class__.__name__
        db = ref.get_service_instance(SERVICE_NAME)
        if db is None:
            log.warning("Cannot access %s from %s", SERVICE_NAME, cname)
            return data

        log.debug("Manipulating the profile: %s", cname)
        data['some_attribute'] = compute(db, user)

        return data
```

**Comment by pdonorio** [comment]
Take your time to use that snippet, and close here if you make it work.

It does already works fine with me.

Edit: we might convert the `Initializer` as well with new `meta.get_customizer_class`...

**Comment by mdantonio** [comment]
It works
