### ISSUE TITLE
Registration flow problem

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#117]
SMTP error in configurations results in 404 not found in registration

**Comment by mdantonio** [comment]
If enabled, the SMTP configuration is now verified at startup (connect + login)

`[CRITICAL restapi.server:291] Bad SMTP configuration, unable to create a client`
OR
`[INFO    restapi.server:293] SMTP configuration verified`

**Comment by pdonorio** [comment]
Awesome 😀
