### ISSUE TITLE
rapydo update does not work because of unstaged files (nice-to-have, not urgent)

### ISSUE THREAD

**Issue by merretbuurman** [rapydo/issues#118]
Hi,
when I use `rapydo update`, it fails to update the main repo as I have unstaged files. The unstaged file that `git status` reports is the ".projectrc" file. Rapydo also complains if I have files unrelated to rapydo in the same directory (e.g. text file with some notes, or get-pip.py).

While it is not too hard to copy _.projectrc_ to another directory and copy it back, it is a bit inconvenient. (Also, the error message **"2018-08-07 14:45:07,438 [WARNING controller.gitter:199] Unable to update http-api repo, you have unstaged files"** does not tell me which directory I need to clean to be able to update. It would help to know that I need to change to _submodules/http-api/_ to clean that one, or to see which files are disturbing.

**Comment by pdonorio** [comment]
The `.projectrc` file is meant to be a configuration file for that particular deploy. 

So I guess it should not be stored in your repo, your should add it to `.gitignore` instead.

**Comment by merretbuurman** [comment]
Makes sense.
(I assume everyone has a `.projectrc`, so maybe it would make sense to add it to the .gitignore globally?)

**Comment by pdonorio** [comment]
Yes, but not sure what globally means :)
It has to be in the root of your rapydo vanilla project, which is global to all subfolders.

**Comment by merretbuurman** [comment]
I meant to have it committed into the existing .gitignore in the repository and then saw that it is already there (https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.3/.gitignore#L5 ).

**Comment by pdonorio** [comment]
👍
