### ISSUE TITLE
A guided tutorial for initialization

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#12]
`init` command has the problem that when launched it just fix everything all at once.

Using `check` we found out that doing a tutorial step by step is the best for the user understanding.

So we should provide something like:
```bash
rapydo init --tutorial

# check for things to be fixed but do not fix them
```

Any blocking element should ask you to add a `fix-next` like:
```bash
rapydo init --tutorial --fix-next

# this will fix the first problem and then stop again if there is another one that follows
```

**Comment by pdonorio** [comment]
An interesting library for docker integration and also tutorials:

https://github.com/ianmiell/shutit
https://ianmiell.github.io/shutit/

**Comment by pdonorio** [comment]
This is important for `rapydo` usability but I guess we're not there yet, really

**Comment by mdantonio** [comment]
Absolutely
