### ISSUE TITLE
Add a command for dumping current compose configuration

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#120]
Helpful to convert rapydo config splitted into files into something usable for swarm/clusters

**Comment by pdonorio** [comment]
Since the normal implementation with the compose library API in python fails to find the files even if specified like the other commands, I've been forced to use the basher to wrap it. Not happy but it works.

**Comment by mdantonio** [comment]
Just a warning: the resulting dumped docker-compose.yml is not portable, since all volumes contains absolute paths

**Comment by pdonorio** [comment]
Good point, I should remove the current dir from it.

**Comment by pdonorio** [comment]
done

**Comment by mdantonio** [comment]
Found a new BUG: the dumped configuration contains every service, a filter should be applied to only keep active services

**Comment by mdantonio** [comment]
It is fine now. See you to the next test!
