### ISSUE TITLE
Projects inheritance

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#127]
We accumulated several use cases for this issue:
1. telethon repository (both NIG and Telethon use a common base)
2. EPOS (built over b2stage http apis by adding few new endpoints)
3. SDC (built over b2stage http apis by adding new endpoints and celery)

Solutions adopted for each case are different, but all unsuccessful

1. two different projects with much duplicated code (duplicatation = evil)
2. fork (the old rapydo-core style, absolutely the worst solution and this is because we removed rapydo-core)
3. everything implemented in the b2stage apis and enabled/disabled (base http api are complicated by a commuty implementation (BAD), not sustainable for other projects (VERY BAD)

Be able to inherit a project from a base project could fix all these cases. As a plus, It will simplify the code at project level (but it will increase the complexity at rapydo level... but I prefer to semplify at user/developer level since a criticism has been made in that sense)

**Comment by pdonorio** [comment]
I'd call this "extends" rather than "project_from" :D 
Does this to work need the extended project code present in the same repo? I guess so :P 

The only problem I see with this option is that it will further decrease the readability of the overall code, split in different places with no defined logic. But the use cases are complicated so it will be difficult to find a better solution...

So go with it, let me know.

**Comment by mdantonio** [comment]
> I'd call this "extends" rather than "project_from" :D

You are very right

> Does this to work need the extended project code present in the same repo? I guess so :P

No, we have to support extention from both projects and submodules. See my previous message for details

> The only problem I see with this option is that it will further decrease the readability of the overall code, split in different places with no defined logic. But the use cases are complicated so it will be difficult to find a better solution...

This should happens if the projects are not true extentions, in other case should simplify the code by splitting responsabilities.

However let's see how things unfold... in every case the result (if working) should be better than the current situation

**Comment by mdantonio** [comment]
Changed the `configuration.read` function to be able to inspect the project_configuration, looking for `extends` and `extends-from` variables in the `project` block

Example:

```
project:
  title: SeaDataCloud HTTP-API
  description: Processing data in SeaDataCloud project
  version: 1.0.5
  rapydo: 0.6.4
  extends: b2stage
  extends-from: projects
```

`extends` default values: variables missing (no extention)
`extends-from` default value: projects. Allowed values: projects, submodules

The syntax should be self-explanatory, the current project extends the b2stage project found in the projects folder (i.e. in the same repository). As alternative the project could be in the submodules folder (i.e. from a different repository)

When `configuration.read` finds a `extends` directive, it load the extra project_configuration file, and returns the mix of projects_defaults + extended project_configuration + project_configuration

**Comment by mdantonio** [comment]
Changed the `backend.yaml` configuration to mount the extended project.

Since the project extention is optional, we should optionally mount the extended project path into the container, but conditional volumes are not allowed in compose and so we should introduce a new level of yaml to do the trick... I prefer to simplify this part by always mounting the extra path. When the project does not extent anything, it will simply mount it-self

Default case (no extention):

before:

```
developer@rapydo_server:/code$ ls
confs	myproject  tests
```

now:

```
developer@rapydo_server:/code$ ls
confs	myproject  no_extended_project tests
```

In case of extention we will find:

```
developer@rapydo_server:/code$ ls
confs	myproject  myproject1   tests
```

Example:

```
developer@rapydo_server:/code$ ls
confs	seadata  b2stage   tests
```

In the same way the extra project_configuration is mounted in confs with name `extended_project_configuration.yaml`. If no extention is set, `extended_project_configuration` will be the same of `project_configuration.yaml`

**Comment by mdantonio** [comment]
Quite completed the separation between b2stage and sdc and from preliminary tests things are working well.
Still missing the cleanup of some portion of code, I keep open this issue in case of required changes at rapydo level

Not tested the separation between b2stage and epos

**Comment by mdantonio** [comment]
Now included separation between b2stage and epos,
kept open for further tests

**Comment by mdantonio** [comment]
Verified on both SDC and EPOS, this task is completed
