### ISSUE TITLE
Services concept

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#13]
How it works now:
```bash
rapydo --services backend,frontend SOME_COMMAND
```

While things are different depending from the command:
```bash
# you can only open a shell on one service
rapydo shell --service backend
# missing parameter should give and error, no default allowed

# launch some services and all of their dependencies
rapydo start --services backend,frontend
# default should be backend or backend,frontend depending if frontend is enabled

# tail logs from some services
rapydo log --services postgres,client
# default like start
```

**Comment by mdantonio** [comment]
> # default should be backend or backend,frontend depending if frontend is enabled

Or proxy, if in production mode

**Comment by mdantonio** [comment]
The default list of services to be started should be configurable somewhere (e.g. as docker-compose enviroment AUTOSTART=true)

The --service flag could be used to override this default (e.g. when someone wants to start only a service or two, instead of the whole stack)

I also think that for a question of readability the service, or list of service could be an option of single commands who require it (in this case the --service parameter disappears)

Examples:

```
rapydo shell backend 
rapydo shell frontend
rapydo control start (this starts the default list of services)
rapydo control start backend,celery
rapydo logs (this means "all logs")
rapydo logs backend,celery

```

**Comment by mdantonio** [comment]
Paolo implemented an  `ACTIVATE: 1` in enviroment to define top-levels services

This is used to start the whole stack (by collecting all ACTIVATED services) and by other management commands (like builds check) by collecting ACTIVATED  services AND all dependencies (recursively extracted from compose)

Now --service flag has no default value

I still think that 

`rapydo shell backend` is more clear and intuitive than `rapydo --services backend shell `

**Comment by pdonorio** [comment]
>  is more clear and intuitive than 

But we have to wait for having all commands to harmonize the design in how we call things, also considering the possibility of moving from `argparse` to `click`.

**Comment by mdantonio** [comment]
More or less: all implemented here (included the change from rapydo --services backend shell to rapydo shell backend)

We can close.
