### ISSUE TITLE
Design a different and up-to-date rapydo v1.0

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#131]
- separate `utils` into `do` and `http-api`
- drop `utils` (note: we can use `loguru` and `parse_it` and similar for replacing some of them)
- `do` should be as optional as possible. The selection of yaml files in the right order is critical here. (can we use a MakeFile instead? Or use pyproject)
- what about `rapydo-confs` and `build-templates`? can it be downloaded in another way? cookie-cutter?
- evaluate `fastapi` to replace `flask` (or as a new option). How does this impact nginx?
- integrate `Vue.js`

**Comment by pdonorio** [comment]
Possible trick for docker build 

```bash
echo "CURRENT_ID=${id -u}" >> .env
```

**Comment by pdonorio** [comment]
note: maybe here we can get a sense of how porting flask to fastapi might work:
https://www.pluralsight.com/tech-blog/porting-flask-to-fastapi-for-ml-model-serving/

**Comment by mdantonio** [comment]
Mostly outdated issue
