### ISSUE TITLE
Pool of docker networks for vanilla projects

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#14]
EUDAT needs a defined subnetwork for postgres.

Create a pull of networks in `do` and pass it as env variables to containers.

**Comment by pdonorio** [comment]
Note: this would solve the infamous bug of `cannot create network` when bring two rapydo projects up in the same machine

**Comment by pdonorio** [comment]
I can't remember anymore why I can't open postgres to all and then restrict the access with the container networking, so I'd make a test with `0.0.0.0/0` and see if all work as expected.

**Comment by pdonorio** [comment]
Removed in `0.5.2`

**Comment by mdantonio** [comment]
> Removed in 0.5.2

Uhmm... so we can remove the following lines from our confs/backend.yaml?

```
    # driver: bridge
    ipam:
      driver: default
      config:
        # Note: use this configuration to match inside internal rules
        # TOFIX: make this an env variable
        - subnet: ${DB_SUBNET}/16
```

**Comment by pdonorio** [comment]
Yep, in core `0.5.2`. We should do this today before releases of packages.
