### ISSUE TITLE
Too many operations executed 

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#16]
rapydo-controller quickly became a mega-powerful tool, able to perform a huge quantity of operations.

Now all rapydo commands execute the full bunch of checks and this leverage two levels of problems:

- some commands are uselessly slow (1)
- some commands could unexpected operations (2)

(1) only init and check should perform all checks. Other commands should simply verify a basic set of things

(2) to understand this point consider the following example based on two rapydo commands. In the second one the user forget to remove an option...

rapydo --force_build control start
rapydo --force_build log

Result: 20 minutes to be able to watch logs 😠

**Comment by pdonorio** [comment]
Taking a look at this now

**Comment by pdonorio** [comment]
This might be depending actually to #20

**Comment by pdonorio** [comment]
Closed with this [new option](https://github.com/rapydo/do/blob/master/rapydo/do/argparser.yaml#L68-L71)

**Comment by mdantonio** [comment]
Another check that should be removed from standard checks is the build_dependencies that took up to 4 seconds

@pdonorio what do you think?

**Comment by mdantonio** [comment]
For now removed the builds check from shell, ssl-certificate and ssl-dhparam
