### ISSUE TITLE
Bower management

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#17]
We need a command to install bower libs. We could implement as proposed in #15

**Comment by mdantonio** [comment]
Added bower install on init

**Comment by mdantonio** [comment]
Added bower update with rapydo update

**Comment by mdantonio** [comment]
As reported in #15 for ssl_certificates, we cannot use the _shell command for the bower commands and the _interfaces command is to be generalized

- the global init and update commands now use a direct Compose,command('run'). They work, but have to be modified to use a wrapper like _intefaces

- the specific bower_install lib and bower_update lib now use _shell (so they do not work and are to fixed after solved the point above)

After solved that we are near to close the issue.

We just have to decide where to store the bower_components folder

I moved bower.json into projects/blueprint/frontend/bower.json but I prefer to not install bower_components into projects/blueprint/frontend to avoid the risk to commit it (and because it is hard to gitignore it, due to the variable component of the path [i.e. $blueprint])

For now I install the libs in a bower_componets folder in the main dir. The problem is that this folder is shared between all projects and can create incompatibilites. To be discussed.

**Comment by pdonorio** [comment]
> the _interfaces command is to be generalized

Should we open an issue for this and decided how?

> We just have to decide where to store the bower_components folder

It should go inside `data/ignored` and ignore that one folder only with `.gitignore`

**Comment by mdantonio** [comment]
> Should we open an issue for this and decided how?

As you wish. But I think that the issue #15 can be fine too, since it is strictly related (and I also reported the problem there because it involves the ssl-certificate command too)

> It should go inside data/ignored 

Ok... but why not simply data/bower_components?

> and ignore that one folder only with .gitignore

The whole data folder is already ignored

**Comment by pdonorio** [comment]
> The whole data folder is already ignored

Ah! :D

**Comment by mdantonio** [comment]
Generalized the _shell and _interfaces methods by creating two functions in Compose (exec_command and create_volatile_container) 

Related commits:

504a73b

5da00a

The new functions are used by:

```
_shell
_interfaces
_ssl_certificates
_custom
_bower
```

For bower everything is done, we can close:

- installation of bower libs with rapydo init
- update of bower libs with rapydo update #18 
- installation of single library with rapydo bower-install --lib libname
- update of single library with rapydo bower-update --lib libname
