### ISSUE TITLE
rapydo update

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#18]
We need a command to update (now we are very good to init the project... Less good to maintain it)

Update should:

- [x] pull from submodules, if some commit is missing
- [x] re-build bower libs, if any (see also #17)

**Comment by mdantonio** [comment]
> re-build bower libs, if any
Done, minor fixes to be solved, but already stated in issues #17 and #15

**Comment by pdonorio** [comment]
I have a use case for this issue, from eudat.
`rapydo update` should:

- switch to a new release (e.g. from 0.5.1 to 0.5.2)
- remove submodules content
- init submodules
- build images

**Comment by pdonorio** [comment]
The EUDAT use case is more of a `rapydo upgrade`

**Comment by pdonorio** [comment]
Wish list 

```bash
$ rapydo upgrade --info

Project information:
- current release is 0.5.1 (referring to rapydo 0.5.2)
- upgradable to 0.6.0
```

and then 

```bash
$ rapydo upgrade 0.5.2

no such version 0.5.2

$ rapydo upgrade 0.6.0

- git branch checkout
- remove submodules content (warning if something has to be committed/pushed)
- rapydo init
- rapydo build images
```

**Comment by pdonorio** [comment]
Remaining her:

- [ ] check for builds / builds template
- [ ] rapydo upgrade

**Comment by pdonorio** [comment]
`rapydo upgrade` will be tracked in EUDAT-B2STAGE/http-api#87

**Comment by pdonorio** [comment]
Missing only "check for builds / builds template"

**Comment by pdonorio** [comment]
> rapydo build -r -f

I have just found out that `rapydo start --build` would rebuild missing images.

To be tested with templates

**Comment by pdonorio** [comment]
Unfortunately templates are not rebuilt when a custom configuration overrides an original docker build.

**Comment by pdonorio** [comment]
Upgrade implemented.

**Comment by mdantonio** [comment]
Update command is quite complet. We should onlye decide if automatically re-build images (when required)

Now update pull repositories and can potentially introduce changes that require re-build. Check is alreadt able to understand a build is required

Current workflow
- rapydo update
- rapydo check to verify if everything is ok
- if suggested by check -> rapydo build

We may introduce an option to automatically build if required

rapydo update --build

without the option update should notify if a build is required

**Comment by pdonorio** [comment]
> We may introduce an option to automatically build if required

Yes. For EUDAT admins to deploy the HTTP-API this would be the default way to go.

**Comment by mdantonio** [comment]
Ok,
so i added a --rebuild option to update

rapydo update --rebuild

This option will automatically rebuild obsolte cached images.

**The problem** is that we only verifies overwritten template images and not all images

This is ok to build missing template images but is not enough to update images

**Comment by mdantonio** [comment]
We are checking both missing and obsolete images in verify_build_cache function that receive as input a builds dictionary, produced by locate_builds

And locate_builds do the following:

```
def locate_builds(base_services, services):

    # TODO: cool progress bar in cli for the whole function START

    # 1. find templates and store them
    templates = find_templates_build(base_services)

    # 2. find templates that were overridden
    response = find_overriden_templates(services, templates)

    # TODO: cool progress bar in cli for the whole function END
    return response
```

Please also note the typo: overriden instead of overwritten. I'm going to fix it

We should split this function.

1. check overwritten template and build what is missing (as now)
2. check all templates and report/rebuild what is obsolete (as now on templates, but extended to everything)

**Comment by pdonorio** [comment]
Are we able to finish this by tomorrow to release 0.5.7 so that EUDAT stable release is based on that one?

**Comment by mdantonio** [comment]
I implemented what proposed

Now both template and used builds are verified

missing templates => built
obsolete templates => rebuilt / reported

missing builds => ignored (will be created at startup)
obsolete builds => rebuilt / reported

**Comment by mdantonio** [comment]
From my side i completed the job

Let's test on EUDAT, if everything is ok you can close this issue

**Comment by pdonorio** [comment]
Tested in production, `rapydo update` and `rapydo update --rebuild` work as expected.

The only comment is: "Unable to update main repo, you have unstaged files".
When we run a project the first thing we do is to change the configuration to have connection to production services. This means that there will ALWAYS be unstaged files, unless we commit this configuration (hoping not to push it by mistake). Probably that could be handled better in the future while we grow our experience with production projects.
