### ISSUE TITLE
Refactor working modes

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#20]
We come from a previous `http-api-base` framework with three *running* modes:

1. debug
  - start things manually
  - verbose output level
  - no proxy
2. development
  - start automatically with reload
  - debug output level
  - proxy with no ssl
3. production
  - start automatically multiworker and no reload
  - info output level
  - proxy with ssl

We must simplify this situation and integrate it better with the new rapydo concepts and controller.

**Comment by pdonorio** [comment]
**Refactor**, don't we like that word?

We come from a progressive situation where things messed up. We did not have an external base and custom configuration (which can now be handled by the rapydo core) and did not have control in checking stuff (which is done now by rapydo do)

We need to make some changes based on this proposal, I will write some things here and eventually we move this into a separate issue.

---

Since `docker-compose.yml` should be moved from backend into rapydo core, we should also create a new final concept for the dualism of "base" and "custom".
I propose now to start thinking about `default(s)` and `vanilla`.

So any file / folder should be positioned inside `rapydo/core` **ONLY** with that in mind. Also see [this comment](https://github.com/rapydo/issues/issues/7#issuecomment-305796809).

e.g.
```bash
# compose defaults, with a base and defaults for working modes
containers/defaults/docker-compose.yml
containers/defaults/development.yml
containers/defaults/production.yml

# template compose for writing your vanilla customization
containers/vanilla/template.yml

# vanilla compose, with whatever name i want
containers/myblueprint/development.yml
containers/myblueprint/whateveriwant.yml

# project configuration (ex `specs`)
project/defaults.yaml
project/vanilla.yaml

# models
models/defaults/somedb.py
models/vanilla/somedb.py
```

p.s. ok vanilla and blueprint as concepts may require some decisions :/

**Comment by pdonorio** [comment]
Anyway, back to the topic.
How are we going to call this modes?

```bash
# development mode (let's forget about debug)
rapydo --mode dev --blueprint b2stage somecommand
# this calls: 
# 1. containers/defaults/docker-compose.yml
# 2. containers/defaults/development.yml
# 3. containers/b2stage/development.yml

# p.s. I think 'dev' should be the DEFAULT value

rapydo --mode dev --blueprint b2stage/whatever somecommand
# only change is:
# 3. containers/b2stage/whatever.yml
```

For production we have the same:

```bash
rapydo --mode prod somecommand
# this calls: 
# 1. containers/defaults/docker-compose.yml
# 2. containers/defaults/production.yml
# 3. containers/vanilla/template.yml
```

**Comment by pdonorio** [comment]
About DEVELOPMENT and PRODUCTION swith...

Let's make the assumption that we may mix DEBUG and DEVELOPMENT mode. In fact they both require to be working as a developer, not in a production environment.

The distance between the two may be fine grained with some extra `do` parameters. e.g.

```bash
# this is debug mode
rapydo --mode dev somecommand

# 'dev' is the default
rapydo --reload  somecommand
# this is same as above but flask is launched in reload multithread mode

# this is current development mode for eudat
# I think 'nossl' should be necessary with a proxy, as a proxy default is to use 80 and 443
rapydo --reload --proxy --nossl somecommand

# shocking proposal towards production 
rapydo --mode prod --proxy somecommand
```

**Comment by pdonorio** [comment]
Now that I left the process in background long enough I am thinking that `dev` mode should also be coupled with some defined task and/or issue.

The great thing of `do` is that it can work with git.
Ideas:

- a command to start developing, like `rapydo flow --label b2stage --version 0.5.1` which should switch the main rapydo fork and all sub repos to the same specific branch `b2stage-0.5.1` or create it if not available
- also an option to associate an issue to the flow, like `rapydo flow --add-issue` which can be converted into a `README` or `note` file in a certain path.

Just saying. Anyway this issue is a good place for adjusting some workflows but of course it cannot be approached before two weeks at least.

p.s. note to self... all repos are: core, backend, frontend, utils, controller

**Comment by mdantonio** [comment]
> Let's make the assumption that we may mix DEBUG and DEVELOPMENT mode. 

I always used debug and production only... never used development... So this mix absolutely do not hurt me

> The distance between the two may be fine grained with some extra do parameters.
....
> shocking proposal towards production based on do options instead of yaml conf

This is an interesting concept. I think that the goal should also be to remove the "if DEBUG / DEVEL / PRODUCTION" statements in the code.
But this is a very very risky way and I feel that we are changing too many things at once. We many projects (more or less) based on rapydo we cannot enter in a long-term instability period, we have to reach some solid checkpoint and then perform other steps... otherwise the gap to port all projects will be too huge and this will be dangerous for services in production.

I agree with most of what you wrote in this issue... but I also think that this not a good moment to affront this.

Let's reach a stable configuration, let's do work all projects on the new basis and then let's move ahead

**Comment by pdonorio** [comment]
not really
