### ISSUE TITLE
All services porting

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#21]
This is not a true rapydo issue... but I really think that the porting (at production level) of every rapydo-service is a strong requirement before to close the first milestone... so i created this issue as checkpoint before any further milestone

- [x] EUDAT
- [x] NIG
- [x] ACC
- [x] EPOS
- [ ] IMC

**Comment by pdonorio** [comment]
Eudat is almost there.
Updates on the others? :P

**Comment by mdantonio** [comment]
> Updates on the others? :P

other services were waiting for this:

> We can now release corresponding packages and apply the same modifications to rapydo/core.

(from issue #23)

**Comment by mdantonio** [comment]
NIG and ACC work well in debug mode. Not yet tested in production mode

EUDAT and EPOS are fully ported?

Can i attach the frontend to EPOS?

**Comment by pdonorio** [comment]
EUDAT is fine. EPOS almost, we need to move in the new branch 'airods' the code and the models from Massimo.

**Comment by pdonorio** [comment]
EUDAT is tested in production by the way, because the certificate was already created.

**Comment by mdantonio** [comment]
> NIG and ACC work well in debug mode. Not yet tested in production mode

ACC tested in production
NIG and IMC tested in debug

> EUDAT is tested in production by the way, because the certificate was already created.

Ok, so we can check it

>  EPOS almost, we need to move in the new branch 'airods' the code and the models from Massimo.

Ok, can i push the frontend stuffs? Into the airods branch?

**Comment by pdonorio** [comment]
> Ok, can i push the frontend stuffs? Into the airods branch?

Yes. Yes.

**Comment by mdantonio** [comment]
Ok, it is done. I'm unable to test it since the branch is missing the EPOS endpoints and models

**Comment by mdantonio** [comment]
Both ACC and NIG are running in production

For IMC I'm waiting for the review meeting (I cannot introduce a major update just few days before the review) => the final IMC update will be done starting from 3th July

**Comment by pdonorio** [comment]
EPOS we take a look tomorrow

**Comment by pdonorio** [comment]
EPOS updated, missing only IMC and then we may close

**Comment by mdantonio** [comment]
IMC is already migrated in debug mode... will be migrated in production in a couple of weeks

However the production migration should not be a problem (production IMC has nothing more than debug IMC + other production services ... so everything should be ok)

I really think that we can close here
