### ISSUE TITLE
Create command

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#22]
For new users a utility like:

`rapydo create myprojectname`

Could be very useful

This command should perform the following steps

1. skip current checks (otherwise we get errors like critical_exit("You are not in a git repository")
2. verify if ./myprojectname; in this case exist with an error
3. git init myprojectname
4. cd myprojectname
5. git add remote upstream repos.core
6. git pull upstream master
7. give istructions to push this repository [*] This step is optional, if you user simply wants to work with a local repository
8. give istructions / guided tour to configure the project (see #12) i.e. edit project_configuration
9. give istructions to init (or simply, do init)

[*] To push the repository, we have to do something like this:
1. create a new repository somewhere -> get your repo URL
2. git add remote origin URL
3. git push

**Comment by mdantonio** [comment]
This issue could be merged with #26

**Comment by pdonorio** [comment]
This is a different approach in fact. We should discuss how to mix them after testing a prototype in #26

**Comment by mdantonio** [comment]
> This issue could be merged with #26

I report here messages from the other issue (now closed)

_From pdonorio:_

Currently we make the creation of a new project based on forking the [`rapydo/core`](https://github.com/rapydo/core) repo.

Usually a much better option is templating. Of course templating in python means [`jinja2`](http://jinja.pocoo.org/) engine. However much more interesting option exists. The most wide used is a project based on jinja, called [`cookiecutter`](https://cookiecutter.readthedocs.io/en/latest/overview.html).

To work with cookiecutter we might [create on the rapydo side a project template ](https://cookiecutter.readthedocs.io/en/latest/first_steps.html) which other user may then use for generate the project. Note: we still might need to create a git repository to give cookiecutter a template, but at least we will finally use some standards.

We can generate the project within Python in `do`, see [src](https://cookiecutter.readthedocs.io/en/latest/readme.html#features):
```python
from cookiecutter.main import cookiecutter

# Create project from the cookiecutter-pypackage/ template
cookiecutter('cookiecutter-pypackage/')

# Create project from the cookiecutter-pypackage.git repo template
cookiecutter('https://github.com/audreyr/cookiecutter-pypackage.git')
```

We can discuss how to create a better way of updating the template for existing projects who become outdated. This is where we should start: audreyr/cookiecutter#784

But we can confirm that there is no "official" updating with cookiecutter, I received a reply on gitter
https://gitter.im/audreyr/cookiecutter?at=594afec6af2cb444279bcc0c

**Comment by pdonorio** [comment]
Since #79 would create a repo for common configurations, then there will be no need to really update the template.

**Comment by mdantonio** [comment]
Now that we removed rapydo core #79 this issue begins to be more important than before

**Comment by pdonorio** [comment]
I agree. We should write down how things would work out with the new conf repo here.

**Comment by pdonorio** [comment]
@mdantonio can you elaborate more here based on the current status of the project?

**Comment by mdantonio** [comment]
Option one: cookiecutter / jinja2 to create all required files and folder and produce as output a rapydo-compliant structure

Option two: copy such structure from a template repo

(git clone blabla/template && cp template/* . && rm -rf template)

**Comment by pdonorio** [comment]
Option 1 is the right one but in our case I would go for the other one :)

**Comment by mdantonio** [comment]
> Option 1 is the right one but in our case I would go for the other one :)

Ok, so it is done:

```
$ rapydo create myproject --template mongo

2018-07-31 13:48:06,687 [INFO    controller.app:67] Do request: create
2018-07-31 13:48:06,688 [INFO    controller.app:1939] You are using rapydo version 0.6.3
2018-07-31 13:48:08,944 [INFO    controller.gitter:94] Cloned repo https://github.com/rapydo/tests.git@0.6.3 as myproject/__template
2018-07-31 13:48:09,777 [INFO    controller.gitter:75] Switched branch to origin/0.6.3 on __template
2018-07-31 13:48:10,004 [INFO    controller.app:1716] Copy from myproject/projects/mongo
2018-07-31 13:48:10,005 [INFO    controller.app:1724] Project myproject successfully created from mongo template

Now you can enter the project (cd myproject) and execute rapydo init
```

```
$ cd myproject/

$ rapydo init

2018-07-31 13:48:42,525 [INFO    controller.app:67] Do request: init
[...]
2018-07-31 13:48:54,781 [INFO    controller.app:1151] Project initialized
```

Available templates are whom implemented in rapydo/tests (and also used for unittests, so all of them should work). Feel free to expand them if needed (by adding more templates or by enhancing the existing ones)

If you think that here could be enough, we can close this issue

**Comment by pdonorio** [comment]
It is. 

SO COOL! 🎊
