### ISSUE TITLE
Things to be checked and/or modified

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#23]
## Remaining for the current milestone

> write correct requirements for each repo

- [x] we should work out the right one for backend

> Files that should be moved from backend into rapydo/core

- [x] what should we do here and most of all with the swagger dir?

> things I broke

- [x] I removed git checks on controller because of switching repos to branch != master
- [x] run and manage now exists on both backend and rapydo core, fix this

> question arising

- [x] crossing projects variables and paths?
- [x] other libs could be moved? e.g. swagger reading/validation

**Comment by mdantonio** [comment]
>  I removed git checks on controller because of switching repos to branch != master

The problem arises from local branches (i.e. branches not yet pushed on repo). In this case the iter_commits fails. Once pushed the branch the problem disappears. 

I added a try/except to skip further checks when local branches are found

**Comment by pdonorio** [comment]
> we should work out the right one for backend

The problem here is to [complete this part](https://github.com/rapydo/http-api/blob/master/setup.py#L23-L33) in the setup file for our backend. Basically we should decide which things to move from the current [requirements](https://github.com/rapydo/build-templates/blob/master/backend/requirements.txt#L41-L50) into the setup.

Notice that I blocked to a certain version, to avoid the work of someone not to work because we than change things. By only depending on `rapydo-http==0.1.1.

**Comment by pdonorio** [comment]
> run and manage now exists on both backend and rapydo core, fix this

They are now only [in eudat](https://github.com/EUDAT-B2STAGE/http-api/tree/master/scripts) 😱 . Rapydo core is missing them.

**Comment by pdonorio** [comment]
> run and manage now exists on both backend and rapydo core, fix this

moving into build_templates

**Comment by pdonorio** [comment]
Note to self:

- `backend/eudat/specs/defaults.yaml` goes into `rapydo.utils`
- `backend/eudat/specs/project_configuration.yaml` there will be one per blueprint

**Comment by pdonorio** [comment]
The new project scaffold:

```bash
├── CHANGELOG.md
├── LICENSE
├── README.md
├── ROADMAP.md
├── confs
│   ├── backend.yml
│   ├── frontend.yml
│   └── nginx
├── data
│   ├── certs
│   └── popolae
├── docs
│   ├── deploy
│   ├── development
│   ├── quick_start.md
│   └── user
├── projects
│   └── eudat
└── submodules
    ├── backend
    ├── builds_base
    ├── prc
    └── utilities
```

**Comment by pdonorio** [comment]
What we moved:

https://github.com/EUDAT-B2STAGE/http-api/commit/4cc15be8a4d80cceb95569390ebda5f1dad7070f?diff=unified

**Comment by pdonorio** [comment]
One thing I'm not sure how to handle is how `do` should know the name of your project when inspecting the current folder.
At that moment it didn't read the configuration but it should look for `projects/eudat/project_configuration.yaml`

**Comment by mdantonio** [comment]
It should be a parameter

rapydo --project mypippo

But i would like to consider a default: the name of the folder in projects IF a single folder is found

rapydo --without-project-option:

if 1 subfolder in /projects -> defaulting to the folder name
if more sub-folders -> give list of projects found and exit

**Comment by pdonorio** [comment]
This is done inside the Eudat repo.
We can now release corresponding packages and apply the same modifications to `rapydo/core`.

This is also a good moment to evaluate if the core has yet reasons to live.

**Comment by pdonorio** [comment]
Packages and fixes have been done.
Should we consider closing?

**Comment by mdantonio** [comment]
> Should we consider closing?

Yes!
