### ISSUE TITLE
Custom rapydo init

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#27]
I have a requirement to extend the init phase with some custom operation executed on the host machine.

If the extention of the init command is cumbersome, it's ok to create a different command and than execute after the init:

```
rapydo init
rapydo custom init
```

The problem is that the current implementation of custom commands ( #15 ) only allows to execute commands on a running container

We need a category of custom commands who simply executes a script (I suppose a python script) put somewhere

Now I have a bash script that I'm able to execute by hande (bash scripts/custom_init.sh). I can convert it in python, than we have to attach it to some command

**Comment by pdonorio** [comment]
> We need a category of custom commands who simply executes a script (I suppose a python script) put somewhere

Probably we need to already do that conversion of `do` commands into Python Classes that extend a basic/abstract/base `Command` class. In that case your "python script" could become a Python class too, to be imported at run time.

**Comment by pdonorio** [comment]
Now http-api package installs a python console command called `restapi`. 
I removed the direct dependency to flask and we use now the python package for command line from the same author of flask, called `click`, see [here](https://github.com/rapydo/http-api/blob/0.5.2/restapi/__commands__.py#L15-L20)

This means that if we import the `cli` variable from `__commands__` we can add new commands with a snippet like:

```python
@cli.command()
def custom():
    """A custom command"""
   pass
```

This would give us the possibility to call `restapi custom`.

What do you think?

**Comment by pdonorio** [comment]
- [ ] install `click` as a requirement
- [ ] Create a Commands base classes which uses `click` to hardcode commands parameters and options
- [ ] Refactor application as a class that reads Commands classes
- [ ] Read base commands in `controller/commands`
- [ ] Read custom commands in `projects/PROJECT_NAME/commands`

e.g.
```bash
projects/eudat/commands
├── __init__.py
└── mycom.py
```

**Comment by mdantonio** [comment]
I report here some comments on issue #15 (now closed)

pdonorio says:

if #56 will be implemented then we are some steps closer to this to be solved.

In fact I've discovered recently that there's another tool similar to our concept of "controller" which in a more generic way gives you a command to "manage" your project. The tool is called manage, reads a YAML and uses click as argparser.

Finally - and that is what's really interesting for us - it uses click + YAML to allow custom commands: https://github.com/rochacbruno/manage#custom-commands

**Comment by mdantonio** [comment]
> Now I have a bash script that I'm able to execute by hande (bash scripts/custom_init.sh). I can convert it in python, than we have to attach it to some command

The situation is still stuck on that.

But can also consider if we really can/want to work on this issue. If we think that in a future we will be able to work on this we can keep open... but to be honest i think that we could close this issue (and also close the porting to click #56) due to a chronic lack of effort

**Comment by pdonorio** [comment]
> due to a chronic lack of effort

Absolutely
