### ISSUE TITLE
Automatic nginx configuration

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#28]
Now we have a fixed nginx configuration in rapydo-core (`confs/nginx/production.conf`)

This configuration works well for any project with backend+frontend and the only customization required by the forked projects is the override of two server-name lines

However, this schema has some limitations:

1. since che hostname is explicitly put into the configurationm it can only be configured at project level (i.e. in the customized production.conf)

2. since the configuration is based on backed+frontend, it is not suitable for projects without frontend

3. projects exposing other services in production (neo4j, flower, swaggerui, ftp) have to configure other sections in the customized version

Some rough solution:

1. Projects deployed on several hosts could create multiple version of nginx configuration and than dynamically mount the right one via compose based the .env variable PROJECT_DOMAIN (Requires an ugly duplication of the configuration and is not suitable if the list of hosts is not known at priori)

2. We could create a couple of configuration: with or without frontend and then mount the right one in compose (Requires a duplication of the configuration)

3. Every project could extend the configuration to add requires sections (The configuration is not centralized and optimized, but is defined by every project... The actual configuration becomes a mere template)

All problems could have a common and more refined solution: dynamically create the nginx configuration before the startup of nginx. This could be done via python by reading some variables:

1. write the right server-name by reading the $DOMAIN env var
2. write the frontend section only if frontend is enabled. If frontend => write the rapydo-core configuration. If not frontend => write the eudat configuration
3. write other sections if services are enabled in production (neo4j, ftp, swaggerui, flower)

**Comment by pdonorio** [comment]
The best option here is to use a docker image with installed `jinja2` to apply templates at startup (a new `dockerentrypoint.sh`) on top of the normal nginx alpine image:

```bash
# initial size = 15.5 MB
docker run -it --rm nginx:1.13.1-alpine ash
apk update
apk add python3
pip3 install --upgrade jinja2 pip
# final size = 76.7 MB
```

**Comment by pdonorio** [comment]
We don't need to work this out as a docker image component, instead we may instruct `do` on doing this, basing on the recent work integrating `jinja2` in our utilities.

**Comment by pdonorio** [comment]
As a plus, after generating nginx configurations we should use some existing tools to check them:
https://github.com/yandex/gixy

**Comment by mdantonio** [comment]
We could create a standalone python script with jinja2 by using something like this:

http://www.pyinstaller.org

Then we can adopt such script here for nginx but also for any other docker build requiring dynamic configurations

**Comment by pdonorio** [comment]
> We could create a standalone python script 

Opened #95 for it

**Comment by pdonorio** [comment]
Still needed but far away (because also waiting for 95)

**Comment by mdantonio** [comment]
> the hostname is explicitly put into the configurationm it can only be configured at project level (i.e. in the customized production.conf)

This was true in 2017... the hostname is dynamic and automatically set at project level (project_configuration) and host level (.projectrc && rapydo option). There is no need to do more here.

> the configuration is based on backed+frontend, it is not suitable for projects without frontend

We added a couple of configurations (backend only, backend + angularjs, backend + angular).

We have a bit of duplication but we don't change these configuration very often (last time 1 year ago) so that isn't a great problem.

Some things could be enhanced, for example to activate optional parts (e.g. to add the access to neo4j web console or to include bad gateways errors)... But from my personal point of view those are minor changes and since the effort here is very limited I really think that no one will ever work on this.

I will reopen if some new use case will require the implementation of this this

**Comment by mdantonio** [comment]
> I will reopen if some new use case will require the implementation of this

To allow the frontend to connect to pushpin websocket we need configure the CSP header by setting $DOMAIN:*
This requires a dynamic change of the configuration based on the env variables

**Comment by mdantonio** [comment]
nginx confs now support env variables (replaced by using envsubst in docker-entrypoint.sh)
