### ISSUE TITLE
env files

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#3]
The command `do` should mix three env files,
possibly from backend, frontend and vanilla.

In python we should do the equivalent of:

```bash
cat backend/env frontend/env ./env > .env
```

**Comment by pdonorio** [comment]
`.env` equivalent for `do.py` is our [project yaml file](https://github.com/mdantonio/rapydo/blob/master/specs/project_configuration.yaml).

Thus we can take a moment now to make this step.

**Comment by pdonorio** [comment]
In composers from backend/frontend we find:

```yaml
image: ${COMPOSE_PROJECT_NAME}/apiserver:template
```

We could make "template" become a python variable for `do` which then saves it into the `.env` file produced at each call

**Comment by mdantonio** [comment]
The mixed .env file should be cached (i.e. created only if not exists) and re-created upon request.

To inform the user that the .env file **should** recreated, the do command could verify if one of the env file (used to mix the final .env) is modified by inspecting the last commits.
The do must also know the last modification date of .env (last modification time from os.stat?)

```
import os

mixed_env = os.stat("./.env")
last_backend_commit = gitter.getLastCommit("backend/env")
last_frontend_commit = gitter.getLastCommit("frontend/env")
last_rapydo_commit = gitter.getLastCommit("./env")

if 
    last_backend_commit > mixed_env.st_mtime or 
    last_frontend_commit > mixed_env.st_mtime  or
    last_rapydo_commit > mixed_env.st_mtime : 

        log.warning("Dear user, your .env is outdated")

```

**Comment by pdonorio** [comment]
We preferred to move env content into YAML configurations.

Both backend and frontend are mixed inside `defaults.yaml`,
while the custom part goes into the `project_configuration.yaml`.

This simplified many things.

**Comment by pdonorio** [comment]
Here's the [logic](https://github.com/rapydo/do/blob/master/rapydo/do/app.py#L223-L258) created
