### ISSUE TITLE
Remove the prefix for packages

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#31]
Starting all the packages with `rapydo.MYPACKAGE` in our framework was not a brilliant idea, as it turned out :)

Will remove this now and force also a synchronization among versions (`0.5.0`)

**Comment by pdonorio** [comment]
This has to be done on:

- [ ] utils
- [ ] controller
- [ ] backend/http

Then projects should update:
- [ ] eudat
- [ ] others

**Comment by pdonorio** [comment]
Produced the first git tag from command line:
https://github.com/rapydo/utils/releases/tag/v0.5.0-beta

And obtained the first release from `tag` auto deployed on Pypi:
https://pypi.python.org/pypi/rapydo-utils/0.5.0

Things are starting to look very good :)

**Comment by pdonorio** [comment]
Released all new 0.5.1 packages version which removed the famous prefix.

I have to say that the HTTP package (`restapi`) was a lot of effort from the starting position we had...

Anyway, to check what we have:
https://github.com/rapydo/issues/blob/master/README.md

**Comment by pdonorio** [comment]
I will test the update for eudat today.

More projects to come with @mdantonio

**Comment by pdonorio** [comment]
Tested passed on eudat at [this commit](https://github.com/EUDAT-B2STAGE/http-api/commit/ef1302d43d753ab0c3056ee84cbd189ca92f99fe) with [this automatic test](https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/255204757)

I have to syncronize some things (this afternoon? tomorrow?) about 0.5.2 in core to follow new eudat specs. Then we can update also @mdantonio projects.

**Comment by mdantonio** [comment]
All projects are now compliant with version 0.5.1

We still have to merge last branches (0.5.1 and 0.5.2?) on master. Conflicts expected because i fixed things directly on master... to be done tomorrow toghter

**Comment by pdonorio** [comment]
If we release the packages are we all good here?

**Comment by mdantonio** [comment]
Release 0.5.2 and test again in production

**Comment by pdonorio** [comment]
Released: https://pypi.python.org/pypi?%3Aaction=search&term=rapydo-&submit=search

**Comment by pdonorio** [comment]
To be tested in production

**Comment by mdantonio** [comment]
> test again in production

Problems in production seem unrelated with the removed prefix, so we can close here

We will open an issue to track production problems and to fix it in the next release (0.5.3)
