### ISSUE TITLE
A development helper

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#33]
I can finally test `invoke` on a new cli tool to ease the strategy of releasing packages.

**Comment by pdonorio** [comment]
This helps/depends on #31

**Comment by pdonorio** [comment]
Note that each package should be tested on travis, so that a github release could trigger a pypi package upload: http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html

**Comment by pdonorio** [comment]
There we started the new helper:
https://github.com/rapydo/develop

**Comment by pdonorio** [comment]
The new process of delivering a package should depend on CI environments:

1. setup travis (from command line)
2. do unittests (`pytest`) on every push
3. compute coverage
4. if everything goes well deploy the package

The last step should be activated only if the pushed branch is also a `tag`•

**Comment by pdonorio** [comment]
Looking for badges I've found this site, very cool:
https://badge.fury.io/for/py/rapydo-utils

**Comment by pdonorio** [comment]
> The last step should be activated only if the pushed branch is also a tag

https://docs.travis-ci.com/user/deployment/pypi/#Deploying-tags

**Comment by pdonorio** [comment]
To think about changelogs (an MD file in `issues`?) and github-pages through `docs` folder.

**Comment by pdonorio** [comment]
Deploy order:

utilities > core > controller > builds > http-api

**Comment by pdonorio** [comment]
This tool should really help people that want to contribute developing rapydo.

Trying to create a protocol to make things easier for anyone to start from zero:

0. Assumption: we will have a working path `DEVPATH` where we install tools and projects
1. Install `develop` and configure `~/.invoke.yaml` to indicate `DEVPATH`
2. `$ develop init` should create `DEVPATH` if not existing and then create `tools` and download inside the latest version (e.g. `0.6.0`) as a sub-directory. Then create also `projects` empty dir inside.
3. `$ develop project b2stage EUDAT-B2STAGE/http-api 0.5.4` should clone https://github.com/EUDAT-B2STAGE/http-api inside the `b2stage` dir. Then clone all rapydo repos in `tools/0.5.4` and link them inside `projects/b2stage/submodules`.

So here's part of an example based on the points above

```bash
# devpath tree example
devpath/
├── projects
│   └── b2stage
│       └── submodules
│           └── utils -> devpath/tools/0.5.4/utils
└── tools
    ├── 0.5.4
    │   └── utils
    └── 0.6.0
```

**Comment by pdonorio** [comment]
Should/could we leverage some other packages like this interesting [hatch](https://github.com/ofek/hatch)?

**Comment by pdonorio** [comment]
We need an init procedure for the development.

How a configuration file would look alike:
```bash
# content of ~/.invoke.yaml

develop:
  # path: /tmp  # DEFAULT
  path: /Users/projects/rapydo
  current-release: 0.6.0
  projects:
    b2stage:
      repo: github.com/EUDAT-B2STAGE/http-api
      branch: 1.0.1
```

The init procedure should create in this case `components` and `projects` and fill them with tools and projects requested in the configuration file.

Also the `--development` option would allow to install `utils`, `do` and `develop` from the latest release paths.

**Comment by mdantonio** [comment]
I added a version here:

https://github.com/rapydo/build-templates/blob/0.6.0/.travis.yml#L27

`[..] build --build-arg RAPYDO_VERSION=0.6.0 [...]`

So devel should also considering the .travis.yaml file in build-templates when replacing versions

**Comment by pdonorio** [comment]
> We need an init procedure for the development

Added

> Also the --development option would allow to install 

To do

**Comment by pdonorio** [comment]
Something I found really interesting reading the python newsletter today:
https://towardsdatascience.com/which-python-package-manager-should-you-use-d0fd0789a250

It seems that this `pyenv` packaging system lets you easily create a python (virtual) environment based on which version of python you prefer + libraries you choose and then to set a default for a directory. So when you enter the directory the environment is automatically activated.

To be investigated if this could be a solution to manage different versions of rapydo in different projects.

**Comment by mdantonio** [comment]
Wow, very very interesting!

**Comment by mdantonio** [comment]
Dev was reading subcomponent urls from projects_defaults in utils

Now this file is no longer available in utils and is moved in rapydo-confs (see #79 for details)

So we need to change how dev retrieve this kind of information

As quick fix we can simply read subcomponents URLs from dev configuration (or hard-code such URLs)

In a future we could consider to merge controller and dev to share the configuration (this is also required for upgrade #71)

**Comment by pdonorio** [comment]
I'm not sure of the direction to take on this component.
Dev exists but I'm not even actually using it.

Since @mdantonio added `rapydo install` I think the only thing missing is the `PR` and `tag` deploy, which is already functioning in the latest version. 

We might close here.

**Comment by mdantonio** [comment]
@pdonorio maybe the only possible improvement is to integrate PR and tag deploy into the controller and remove dev

**Comment by pdonorio** [comment]
In `develop` I took the shortcut and used the `git` binary instead of the python git library:

- tags are [here](https://github.com/rapydo/develop/blob/master/develop/git.py#L87-L128)
- PR used `hub` command (you have to install it) [here](https://github.com/rapydo/develop/blob/master/develop/mytasks/release.py#L53-L76) 

It would be awesome to have that in the controller but I fear it's difficult (if not impossible for the `PR` case)
