### ISSUE TITLE
Testing spark

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#34]
We could test Spark launched as a client from a celery worker to a real hadoop cluster.

**Comment by pdonorio** [comment]
To add the spark ecosystem to a celery worker we need to modify the celery docker image, see [the jupyter image](https://github.com/jupyter/docker-stacks/blob/master/pyspark-notebook/Dockerfile#L20-L24) to take inspiration.

**Comment by pdonorio** [comment]
An example for the code is available [here](https://github.com/pdonorio/notebookers/blob/master/notebooks/VCF-Spark-example.ipynb)

**Comment by mdantonio** [comment]
I extented my local celery build starting from the linked jupyter image and added a very basic Spark computation into the celery task... Everything works very fine

Then I tried to understand how to connect pyspark to neo4j.

This should be the state of the art about this connection:
https://github.com/neo4j-contrib/neo4j-spark-connector

It seems that Python remained a bit behind Java ... to be further inspected trying to do some tests

**Comment by mdantonio** [comment]
No effort for this in a reasonable future
