### ISSUE TITLE
Update to Python 3.6.2

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#41]
Python 3.6.2 is out:
https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-2

Test it where possible:
- controller on travis
- http-api backend docker image
- others?

**Comment by pdonorio** [comment]
With the ubuntu image `17.10` python3 comes bundled `3.6.2`.

I'll try to update our image in the next rapydo release and test it on EUDAT.

**Comment by pdonorio** [comment]
Note: on travis python 3.6.2 gives error if we try to update setuptools and pip in the `requirements.txt` file. It works instead on our ubuntu image.

I've found a similar issue here: https://github.com/pypa/setuptools/issues/1101. The workaround is to upgrade setuptools separately before installing requirements...

**Comment by pdonorio** [comment]
With the previous workaround the whole set of tests on `0.5.4` based on python 3.6.2 passed.

Now we should probably continue with `celery`. Ping @mdantonio.

**Comment by mdantonio** [comment]
> Now we should probably continue with celery

I'm unable to test with celery now...

Once #53 will be completed I will implement a configuration to also test celery

**Comment by mdantonio** [comment]
Are we using python 3.6.2 now?

This issue can be closed?

**Comment by pdonorio** [comment]
I am using `3.6.3` by just rebuilding the image
