### ISSUE TITLE
Easier way to add a new endpoint developing the API

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#43]
We may work for this with the new `restapi` command of the HTTP API base.

e.g. `restapi add --endpoint myfeature` should add:

- the swagger directory with a filled template to a file `myfeature.py`
- the `myfeature.py` template with a class `Myfeature` extending the API base class
- the `test_myfeature.py` template for a unittest with a class `TestMyfeature` extending the unittest base class

**Comment by pdonorio** [comment]
Actually this can be done with the controller too from outside.
Which option is better? `rapydo` or `restapi`?

**Comment by mdantonio** [comment]
Probabily the  controller... In this way it could also add some code to the frontend, if required. 
Furthermore create such files and folder from outside the container should be better for permissions

**Comment by pdonorio** [comment]
Fine then! Let's do this on the controller, using `jinja2`. I have to read its documentation again :P

**Comment by pdonorio** [comment]
Ok, available with `0.5.2`

**Comment by pdonorio** [comment]
Add: 
- how to get parameters 
- how to return an error
