### ISSUE TITLE
Badge for non packaged repos

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#44]
We can use the badge fury website: 
https://badge.fury.io/for/gh/rapydo/build-templates

The only version semantic that worked for build was `X.Y.Z`(where all the letters are integers) which is also how we name development branch at the moment.
One thing that we may have if we follow this rule for tags too is that a tag and a branch have the same name so I don't know what problems may arise here.

**Comment by mdantonio** [comment]
That's ok... we can add this information to the development tool...

The issue can be closed?

**Comment by pdonorio** [comment]
Only when we have the tag 0.5.2 on the core too. Tomorrow.

**Comment by pdonorio** [comment]
Solved with https://shields.io/
