### ISSUE TITLE
Creation and handling of users

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#48]
We have a common endpoint to handle users (Profile) but this endpoint leverages on the basic User Model. Since i changed the model I also have a totally customized enpdoint (*) to create and modify users and this is quite bad... We should find a way to generalize the User creation and modification.
This problem is also to linked to init phase ( [#2 (rapydo/issues#8)](https://zube.io/rapydo/rapydo/c/2) )

**Comment by pdonorio** [comment]
This is a difficult task. See you after the summer!

**Comment by mdantonio** [comment]
To implement such endpoint we need several modication

First of all we have to centralize the user creation for every auth method. Neo4j-auth already has a create_user method. SqlAlchemy and Mongo directly create user. Now i added a create_user method also for sql and mongo.

To test this preliminary modification we need to implement better unittests for restapi ( #53 )

the create_user function is also responsible for:
- hash the password (=> removed the password hashing in init_users)
- defaulting auth method ( => removed "credentials" in init_users)
- link the user to roles

As a plus: not required for registration, but usefull to have an omogeneous interface: we have to extend the create_role function (from neo4j-auth) in sql and mongo

**Comment by mdantonio** [comment]
Create a POST /api/profile endpoint to register user (not yet fully working)

The implementation of this endpoint required two modification:

- we need to create custom FormDataParameter at base level (restapi/swagger/params_models.yaml) to be extended in vanilla (projects/backend/swagger/params_models.yaml)

- we need to handle / validate input parameter based on the endpoint schema

**Comment by mdantonio** [comment]
> we need to create custom FormDataParameter at base level (restapi/swagger/params_models.yaml) to be extended in vanilla (projects/backend/swagger/params_models.yaml)

Replaced the current mix of swagger configuration (very rough) with the utilities.configuration.mix function

I also modified this function to be list-aware (it was able to mix dictionaries, not lists)

Now FormDataParameter in restapi/swagger/params_models.yaml can be extended in projects/backend/swagger/params_models.yaml to manage fields from extended User models during registration

**Comment by mdantonio** [comment]
> we need to handle / validate input parameter based on the endpoint schema

Moved in restapi/rest/definition.py some methods implemented in restapi/services/neo4j/graph_endpoints

Such methods are not really related to graph database

**Comment by mdantonio** [comment]
ops, issue closed for mistake, reopened

**Comment by mdantonio** [comment]
Next step: we have to decorate the user creation with custom (vanilla based) pre and post operations

example of pre_operation = generate a password the the irods certificate (passphrase saved in the user node)

example of post operation: link the created used node to a group node

**Comment by mdantonio** [comment]
> Next step: we have to decorate the user creation with custom (vanilla based) pre and post operations

> example of pre_operation = generate a password for the irods certificate (passphrase saved in the user node)

> example of post operation: link the created user node to a group node

Added a class (Customizer) in initialization.py (vanilla based)

Customizer implements a custom_user_properties method to expand userdata with custom stuffs (e.g. default irods_user)

This partially solves this point (applied to both nig project)

**Comment by mdantonio** [comment]
Most is done here, enough for now
