### ISSUE TITLE
unittest

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#5]
Decide the future of unit tests inside Rapydo

1. Check scenarios (and if mocking is available)
2. Check pytest, plugins and mocking
3. If 2 and 3 fails, keep nose and integrate it with swagger

**Comment by pdonorio** [comment]
Note: this one is related to already existing tests and how to improve them for the REST HTTP API server component and their blueprints.

I opened #11 to track the unittests for `do` which are quite different.

**Comment by mdantonio** [comment]
I moved this issue from MVP milestone to the next one... We already have enough for MVP

**Comment by mdantonio** [comment]
We migrated to pytest for controller, develop and utiles

http-api is still bound to nose2 but i intend to migrat to pytest in the future

I think that we can close here (Scenario, for me, is not really a solution at rapydo level, can be a good tool at project level, i.e. not to be centralized in rapydo so out of topic here)
