### ISSUE TITLE
Avoid default credentials for production startup

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#50]
as subject

**Comment by mdantonio** [comment]
We should work on this issue

**Comment by mdantonio** [comment]
Yes, it is

**Comment by pdonorio** [comment]
Can we mix this with the need to populate the project at the first startup?

**Comment by mdantonio** [comment]
To be honest: i don't know ... If you think that is possible to integrate this check on the init, for me is ok

**Comment by pdonorio** [comment]
Yes it is possible. I'll do it.

**Comment by pdonorio** [comment]
I'm not sure I can! xD

Can you @mdantonio? 
Otherwise we can close, not implemented up to now means not necessary (for now).
