### ISSUE TITLE
Install prerequisites

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#52]
We should take https://get.docker.com/ as example to make things easier on installing the framework and cloning a forked project:

- [x] create a `sh` script
- [x] launch the script in *one-liner* form of `wget -O - http://bit.ly/rapydo-prerequisites | sh`
- [ ] check for `git`, `python3.4+` and `pip3`, linking official documentation if missing
- [ ] if not root, ask for sudo, otherwise virtualenv
- [ ] install the controller
- [ ] `rapydo clone EUDAT-B2STAGE/http-api --destination eudat` to clone the repo and  suggest then `tutorial`

**Comment by pdonorio** [comment]
Note, from https://web.archive.org/web/20170608055745/https://get.docker.com/:

```bash
# This script is meant for quick & easy install via:
#   'curl -sSL https://get.docker.com/ | sh'
# or:
#   'wget -qO- https://get.docker.com/ | sh'
```

**Comment by pdonorio** [comment]
We can start from the work on eudat, see [here](https://github.com/EUDAT-B2STAGE/http-api/blob/0.6.0/data/scripts/prerequisites.sh)

**Comment by pdonorio** [comment]
ping @mdantonio

**Comment by pdonorio** [comment]
I expect this script to take somehow a parameter. In fact we need to specify the version of the rapydo components to install (e.g. utils and do) for the specific project. What do you think?

**Comment by pdonorio** [comment]
Added compatibility with OS X. Since we cannot use any package manager we suggest to install python from the official resources.

**Comment by pdonorio** [comment]
Latest version is here: 

https://github.com/rapydo/do/blob/0.5.4/install_prerequisites.sh

**Comment by mdantonio** [comment]
> I expect this script to take somehow a parameter. In fact we need to specify the version of the rapydo components to install (e.g. utils and do) for the specific project. What do you think?

Off course... to add parameter simply edit lines 38-51

https://github.com/rapydo/do/blob/0.5.4/install_prerequisites.sh#L38-L51

E.g. replace mirror with version. We should maintain a default value to install latest stable version

**Comment by pdonorio** [comment]
The parameter should be version/branch and the default could be `master` of course

**Comment by mdantonio** [comment]
Ok, I updated the script (directly on your branch 0.5.4)

```
$ sh install_prerequisites.sh
[...]
Selected version: master

$ sh install_prerequisites.sh --version 0.5.4

[...]
Selected version: 0.5.4
```

When using wget/curl you can do that:

`curl -sSL https://raw.githubusercontent.com/rapydo/do/0.5.4/install_prerequisites.sh | sh -s version 0.5.4`

Please note that the passed parameter here is `version` and not `--version`
This is because this command gives me an error:

```
sh: 0: Illegal option --
curl: (23) Failed writing body (2169 != 2759)
```

So I simply added "version" as alias "--version" inside the script and you can do 
that: `sh install_prerequisites.sh --version 0.5.4`
or that `sh install_prerequisites.sh version 0.5.4`

**Comment by mdantonio** [comment]
You added a check of mac, but this check fails on ubuntu:

`sh: 10: [: Linux: unexpected operator`

For now I'm unable to debug that

**Comment by pdonorio** [comment]
> You added a check of mac, but this check fails on ubuntu

Uhm, ok, I will double check that with docker running ubuntu (16.04?)

**Comment by pdonorio** [comment]
Maybe this interesting tutorial will help us:
https://medium.com/@settermjd/how-to-use-docker-to-simplify-writing-multi-distro-shell-scripts-4eecb094ce0a

**Comment by pdonorio** [comment]
I do not like this approach anymore. Multi platform is too hard for our current effort.

Let's switch to a preferred OS (ubuntu, 18.04 to be released in a couple of months), and produce the packaging (`.deb` package) to do the job for a person wanting to deploy.

**Comment by pdonorio** [comment]
Switching to #91
