### ISSUE TITLE
Compose defaults

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#54]
I implemented a piece of code to compute compose options defaults, see [here](https://github.com/rapydo/do/blob/0.5.3/controller/compose.py#L178-L189).

To be tested

**Comment by mdantonio** [comment]
This issue is still required?
What to do with that piece of code you spoke about?

**Comment by pdonorio** [comment]
This piece of code should help us avoid to write all those options before sending a command. We could check if it works and decide then if useful, I guess it could.

**Comment by mdantonio** [comment]
Ok, so i add this issue to 0.6.1 project

**Comment by mdantonio** [comment]
I tested the get_defaults function... what I obtain is the command usage:

We have to parse the docstring to obtain info about the command default? This is a mess...

**Comment by pdonorio** [comment]
Uhm, no that was not what it was like. There was nothing to parse when I tested it, there was a dictionary with defaults. It's probably still somewhere inside there and of course we have to get it.

Also, if it looks like it's not the effort we may close.

**Comment by mdantonio** [comment]
You retrieve docstring by using `inspect.getdoc(object)`

And this function returns a string:

`Get the documentation string for an object, cleaned up with cleandoc(). If the documentation string for an object is not provided and the object is a class, a method, a property or a descriptor, retrieve the documentation string from the inheritance hierarchy.`

**Comment by mdantonio** [comment]
I just tried again and found a strange behaviour:

When applied to "exec_command" the function returns the docstring as string and exit

When applied to "run" the function returns the docstring as dictionary and continue

So run works, exec_command not

exec_command is equivalent to exec command line

`self.get_defaults('exec_command')` === `docker-compose exec -h`

I tried to ask for exec, but I obtain: 

```
    docstring = getdoc(getattr(TopLevelCommand, command))
                │              │                └ 'exec'
                │              └ <class 'compose.cli.main.TopLevelCommand'>
                └ <function getdoc at 0x7fa33d7fc1e0>
AttributeError: type object 'TopLevelCommand' has no attribute 'exec'
```

What may originate this difference?

**Comment by pdonorio** [comment]
I've no idea why that part is acting like this.

Run and exec are quite different concepts, so probably it's just how compose behave but it's not documented as usual...?

**Comment by pdonorio** [comment]
We can make a new test together in two days. Booked

**Comment by pdonorio** [comment]
On hold, waiting for next compose update

**Comment by pdonorio** [comment]
Should we test again?

**Comment by mdantonio** [comment]
Tested and nothing is changed. Same issue, we obtain the usage as string (with `inspect.getdoc`) but we are unable to convert it into a dictionary (with `compose.cli.docopt_command.docopt_full_help`)

Here the docopt_full_help function:

https://github.com/docker/compose/blob/master/compose/cli/docopt_command.py

```
def docopt_full_help(docstring, *args, **kwargs):
    try:
        return docopt(docstring, *args, **kwargs)
    except DocoptExit:
        raise SystemExit(docstring) <-- the function raises this SystemExit
```

I suppose that the docstring contains something wrong... it is hard to understand what

Here the received docstring:
```
Usage: exec [options] [-e KEY=VAL...] SERVICE COMMAND [ARGS...]

Options:
    -d, --detach      Detached mode: Run command in the background.
    --privileged      Give extended privileges to the process.
    -u, --user USER   Run the command as this user.
    -T                Disable pseudo-tty allocation. By default `docker-compose exec`
                      allocates a TTY.
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
    -e, --env KEY=VAL Set environment variables (can be used multiple times,
                      not supported in API < 1.25)
    -w, --workdir DIR Path to workdir directory for this command.

```

**Comment by pdonorio** [comment]
Edit: I hate how it works now, so I'll implement at least a little helper

**Comment by pdonorio** [comment]
Helper wasn't that hard, see [implementation](https://github.com/rapydo/do/blob/0.6.3/controller/compose.py#L228-L255).

And [see example](https://github.com/rapydo/do/blob/0.6.3/controller/app.py#L1800-L1804) of how I used it.
