### ISSUE TITLE
Project names aren't free: reserved names

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#57]
A project in vanilla cannot be created with any name, because there are a huge number of reserved names and will lead to unpredicatable effects (but basically to non-working backends)

The problem arises from the mount of vanilla code in the main backend dir ( /code)

If i use a project name that matches some python library used in the backend, i'm overriding the import from python libs to the local folder

Just as example:

rapydo --project os start

=> i will mount the project os on /code/os

After that the "import os" statement will not import the real os library, but instead my vanilla code.

os.path will clearly fails at runtime

I discovered this bug while implementing the multiple tests for backend ( #53 ) and trying to create a "neo4j" project

Just a list of reserved names (it is not not exhaustive nor precise, just obtained with a combination of grep and awks)

```
abc
attr
base64
better_exceptions
bravado_core
celery
click
collections
datetime
dateutil
elasticsearch_dsl
email
errno
flask
flask_injector
flask_oauthlib
flask_restful
flask_sqlalchemy
functools
glob
hashlib
hmac
injector
inspect
io
irods
iRODSPickleSession
json
jwt
logging
neo4j
neomodel
os
pickle
plumbum
pymodm
pymongo
pyotp
pyqrcode
pytz
random
re
smtplib
socket
sqlalchemy
string
submodules
sys
time
unittest
werkzeug
```

**Comment by mdantonio** [comment]
I see two solutions to that problem:

1) Since it is difficult to understand the problem, we should verify at controller level if you are using a reserved name (the list of reserved names can be static [easy] o dynamically retrieved from backend code [hard])

2) Do not mount vanilla code directly in /code but instead in a subfolder:

```
now: /code/$VANILLA_PROJECT

then: /code/projects/$VANILLA_PROJECT

```

This solution is non retrocompatible, but it is cleaner than the first one
Furthermore this solution could allow to mount the whole projects folder in /code [not only the selected project) and this could be very useful to share common code between different projects (e.g. NIG and ACC)

**Comment by mdantonio** [comment]
Found another problem with project name: they cannot contains underscores (e.g. celery_test)

because

rapydo --project celery_test something is not a valid command, since:

```
ValueError: Wrong "celery_test" option provided.
Arguments containing '_' are not allowed.
Use '-' instead
```


So we have to avoid names with _ or we should change this kind of check on controller (it is really required?)

**Comment by pdonorio** [comment]
> So we have to avoid names with _ or we should change this kind of check on controller (it is really required?)

I was trying to follow the standards there but it created more problems than good things. Also I don't know how click works on this, we should probably check.

You can change this behaviour if you need :)

**Comment by mdantonio** [comment]
Since you enhanced the check with this commit:

https://github.com/rapydo/do/commit/f3af81bc45370e3e84f8a0340f06cc877a985330

The issue can be closed
