### ISSUE TITLE
Swagger models

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#59]
Now we put swagger models ("definitions:" block) in 

```
restapi/swagger/params_models.yaml
project/$project/backend/swagger/params_models.yaml
```

and we do not specify the "definitions" key, automatically added in 

```restapi/swagger.py:337```

This choice does not allow to define reusable parameters ("parameters:" block) and responses ("responses:" block)

as described in:

https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-3-simplifying-specification-file/

To fully support swagger reusable definitions we should:

- explicitly add definitions: in our models file, to be able to also put parameters and responses (note: we also have the custom key "FormDataParameters")

- rename swagger/params_models.yaml into swagger/models.yaml (because we no longer have parameters only, but also other models)

- modify restapi/swagger.py

now:

```
output['definitions'] = self.read_definitions()

def read_definitions(self):
    [...]
    data = mix(base_model, custom_model)

    self._fdp = data.pop('FormDataParameters', [])

    return data
```

after:

```
models = self.get.models()
output['definitions'] = models.get("definitions", {})
output['parameters'] = models.get("parameters", {})
output['responses'] = models.get("responses", {})
self._fdp = models .get('FormDataParameters', [])

def models(self):
   [...]
   return mix(base_model, custom_model)
```

**Comment by mdantonio** [comment]
I modified swagger to extract from the model file "definitions" block (this was the old default), "parameters" and "responses" (plus our custom "FormDataParameters"

To ensure back-compatibility if swagger does not find any of these block, it assumes the old syntax and put everything into the definitions block (as before). A warning is raised. This back-compatibility implementation will removed in the future, so please fix your swagger file

I also renamed the parameter_models into models. This change is not back-compatible at all, so please rename your model file


cd projects/YOURPROJECT/backend/swagger
git mv params_models.yaml models.yaml

open your models.yaml and change from:

```
SeveralStuff
[...]
FormDataParameters:
    [...]
```

to:

```
definitions:
    SeveralStuff
    [...]
    FormDataParameters:
        [...]
```

I already fixed on backend, rapydo core, NIG and IMC

@pdonorio please give me a feedback on EUDAT and EPOS

I also wait for a feedback from IMC Team to test responses and parameters

**Comment by pdonorio** [comment]
I've updated eudat/b2stage in the branch 0.6.2
