### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#60]
Here's an issue to close/open in case we want to monitor important python packages updates for dependencies

**Comment by pdonorio** [comment]
Compose has reached [`1.16.0`](https://github.com/docker/compose/releases/tag/1.16.0).

I will probably add it to rapydo `0.5.5` next week.

**Comment by pdonorio** [comment]
Compose breaks everything with the latest release. I think they use some sort of relative importing in python (very bad) which does not work when you invoke it from another code. `ansible` has shown the same issue with compose (the error is about importing a function called `splitdrive`).

So we stick with `1.15` and upgrade only docker from 2.4 to 2.5

**Comment by pdonorio** [comment]
Python 3.6.3 is out:
https://www.python.org/downloads/release/python-363/

**Comment by mdantonio** [comment]
(committed on the wrong issue)

**Comment by pdonorio** [comment]
Update swagger ui from 2.x to 3.x

**Comment by mdantonio** [comment]
> Compose breaks everything with the latest release.

Compose 1.17.0 released 4 days ago. Could we check if this version works for us?
This new version should include a fix to set privileged mode flag from environmen, required for Gitlat CI (very important)

**Comment by pdonorio** [comment]
Tested successfully in branch `0.6.0`. Accepted and pushed in `do` repo setup.

**Comment by mdantonio** [comment]
1.17 works well, this is good (I were not happy to be stuck on 1.15)

However they don't introduced the fix for Gitlab CI with this release, but it is already merged on master and will be introduced with the next one (1.18) (already performed some basic tests and the fix works)

**Comment by pdonorio** [comment]
> Python 3.6.3 is out

Ubuntu 17.10 is already linking Python 3.6 packages to Python 3.6.3.
So the latest build has Python 3.6.3

**Comment by mdantonio** [comment]
That's great. With 1.18 we can continue with our tests con Gitlab CI

Let's do the upgrade on 0.6.0?

**Comment by pdonorio** [comment]
Sure

**Comment by mdantonio** [comment]
Done some preliminary tests with compose 1.18

This compose requires docker>=2.6.1

Last stable docker is 2.7.0 but this version requires requests>=2.14 and we are still stuck at 2.11

Docker 2.6.1 is fine for both compose 1.18 and requests 2.11 =>

Configured in setup:

```
        "docker-compose==1.18",
        "docker==2.6.1",
        "requests==2.11.1"
```

But we know that the next upgrade will also require an update of requests (Could we check again this lib? We cannot solve the blocking problems?)

However after this preliminary test i found that compose added a new option to run

`    -l, --label KEY=VAL   Add or override a label (can be used multiple times)`

So the controller fails to start containers:

```
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 1141, in build_container_options
    if options['--label']:
KeyError: '--label'
```

We could add this default when calling run... but this could be a good moment to work on Compose defaults #54  ... what do you think @pdonorio ?

**Comment by pdonorio** [comment]
I'm in favour of fixing #54

**Comment by pdonorio** [comment]
Python 3.6.4 is out
https://www.python.org/downloads/release/python-364/

**Comment by mdantonio** [comment]
> I'm in favour of fixing #54

Due to the effort required to implement #54 we postponed the issue to the next release.

Here we upgraded compose to 1.18 by adding the missing parameters


Just remember that:

> Compose 1.18 requires docker>=2.6.1
> 
> Last stable docker is 2.7.0 but this version requires requests>=2.14 and we are still stuck at 2.11
> 
> Docker 2.6.1 is fine for both compose 1.18 and requests 2.11
> 
> But we know that the next upgrade of compose will also require an update of requests (Could we check again this lib? We cannot solve this blocking problem?)
>

**Comment by mdantonio** [comment]
> Could we check again this lib? We cannot solve this blocking problem?

I verified that compose 1.18 is now compatible with latests requests (2.18.4).

Updated our requirements, no longer stuck on requests 2.11

**Comment by pdonorio** [comment]
Compose 1.19 is out: https://github.com/docker/compose/releases/tag/1.19.0

**Comment by mdantonio** [comment]
Compose 1.19 introduced new options, for example added `--always-recreate-deps` to docker-compose `up`

Let's decide if try to work again on #54 or fix our commands by adding new options as done for 1.18

**Comment by pdonorio** [comment]
Let's leave this issue open for next updates

**Comment by pdonorio** [comment]
Compose reached `1.20.1`

**Comment by pdonorio** [comment]
Flask reached 1.0 :)
https://github.com/pallets/flask/releases/tag/1.0

We should test it on 0.6.2

**Comment by pdonorio** [comment]
Python is on 3.7
https://realpython.com/python37-new-features/

We should add it as well as Flask 1.0.2

**Comment by pdonorio** [comment]
Ok we are using Flask 1.0.2 and python 3.7 is still on beta for ubuntu and alpine.

But I used this as an excuse to build a lighter backend image, upgrading to ubuntu `18.04 LTS` see:
- confs: 0ad05b1891ce40ab4281a68a96804bf29ca7c135
- builds: 6c5fe49dbd9c162f22c0c6f4aac3ffc6a62389e7 

To activate it put `BACKEND_BUILD_MODE: lightbackend` in your project configuration!

**Comment by mdantonio** [comment]
it works very fine

Maybe we should considering this version as the default and add a backend-irods

**Comment by pdonorio** [comment]
You're right. Let me know if you do that and when.

**Comment by mdantonio** [comment]
We can do that quite quickly

1. rename backend -> backend-irods (are dash allowed in docker image names?)
2. rename lightbackend -> backend
3. change projects_defaults BACKEND_BUILD_MODE: backend
4. I will add BACKEND_BUILD_MODE: backend-irods to b2stage and Telethon
5. fix build-templates docker-compose.yaml and .travis to include the new image to unit tests

**Comment by mdantonio** [comment]
All done, you can test it

> I will add BACKEND_BUILD_MODE: backend-irods to b2stage and Telethon

b2stage unittests are running

**Comment by pdonorio** [comment]
I'm not sure I want to keep this issue open but rather open an issue when an upgrade is important.

Also switching to alpine is not a huge priority. 

Can we close?

**Comment by mdantonio** [comment]
Yep
