### ISSUE TITLE
Custom "bad gateway" web page

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#61]
If for performance/other problems issues the production backend fails nginx gives back "502 bad gateway"

We should create a custom page to tell the user "unreachable API" as a response:
https://stackoverflow.com/a/7796429

**Comment by pdonorio** [comment]
In eudat, fixed following [this guide](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04).

Note: it's not very comfortable to set up a non HTML response detecting if it's a browser in nginx. See also: https://gist.github.com/ddre54/10996786

This issue may be closed, and use it as instructions for any other project that want to add the same kind of functionality. This code cannot be used in a more general way since the nginx production file is in the core fork.

**Comment by mdantonio** [comment]
> This code cannot be used in a more general way since the nginx production file is in the core fork.

It could be included in the dynamic nginx configuration? (issue #28)

**Comment by pdonorio** [comment]
Absolutely, you are right
