### ISSUE TITLE
restapi wait -> None port

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#64]
We have some service (i.e. celery) who does not have PORT and HOST and this brings to the following error:

```
    port = int(myclass.variables.get('port'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Solution one: rename BROKER_HOST and BROKER_PORT as HOST and PORT => all services must have PORT and HOST (in this case the script should provided a clearer error to make debugging easier)

Solution two: make restapi wait smarter and able to find a solution (if PORT is not found, search for other %PORT% variables)

As a plus: better_exception was not installed for restapi wait, to be added

**Comment by mdantonio** [comment]
This problem is also found in the celerytest project #53 

Please after fixing here, re-enable the celery test

**Comment by mdantonio** [comment]
For now I put a temporary fix (based on solution one, by creating a couple of alias variables) for IMC and rapydo_core/celerytest projet

(changed in common.yaml)

**Comment by pdonorio** [comment]
Possible solution:

Search for `${SERVICE}_*_HOST` and `${SERVICE}_*_PORT` (only if failing with normal name)

**Comment by mdantonio** [comment]
Implemented this:

> Search for ${SERVICE}_*_HOST and ${SERVICE}_*_PORT (only if failing with normal name)

Log example:

```
[WARNING restapi.__commands__:179] Unable to find HOST variable for celery
[INFO    restapi.__commands__:183] Using broker_host as HOST variable for celery
[WARNING restapi.__commands__:187] Unable to find PORT variable for celery
[INFO    restapi.__commands__:191] Using broker_port as PORT variable for celery
[DEBUG   restapi.__commands__:199] Socket broker.dockerized.io:4369
[VERBOSE restapi.__commands__:126] Waiting for celery
[INFO    restapi.__commands__:143] Service celery is reachable
```
