### ISSUE TITLE
How many times do we have to specify the rapydo `version`?

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#65]
In my development branch i changed several @0.5.4 into 0.6.0 to make it fully working... I don't known if effectively all changes are required, but the number is really huge!

Some are strictly required (e.g. all `__version__ = '0.6.0'`)
Other can be managed by using the develper tools #33 

But I hope that some could be simplified somehow

Here's a list

# rapydo/core

_projects/*/project_configuration.yaml (in core we have 6 projects)_
```
    5:   version: "RAPyDo framework v0.6.0-beta"
    6  
    7  variables:
    8    repos:
    9      rapydo:
   10:       branch: 0.6.0
   11      utils:
   12:       branch: 0.6.0
   13      backend:
   14:       branch: 0.6.0
   15      build-templates:
   16:       branch: 0.6.0

```

_projects/*/requirements.txt (this file is not in the other 5 projects... to be added?)_
```
    2: git+https://github.com/rapydo/utils.git@0.6.0
    3  requests==2.11.1
    4: git+https://github.com/rapydo/do.git@0.6.0
```

# rapydo/http-api

_dev-requirements.txt_
```
    3: git+https://github.com/rapydo/utils.git@0.6.0
    4  requests==2.11.1
    5: git+https://github.com/rapydo/do.git@0.6.0
```

_restapi/__init__.py_
```
  5: __version__ = '0.6.0'
```

# rapydo/templates

_backend/requirements.txt_
```
   14: git+https://github.com/rapydo/utils.git@0.6.0
   15: git+https://github.com/rapydo/http-api.git@0.6.0
```

_celery/requirements.txt_
```
    9: git+https://github.com/rapydo/utils.git@0.6.0
   10: git+https://github.com/rapydo/http-api.git@0.6.0
```

_restclient/requirements.txt_
```
    7: git+https://github.com/rapydo/utils.git@0.6.0
```

# rapydo/utilities

___init__.py_
```
    5: __version__ = '0.6.0'
```

# rapydo/controller

_dev-requirements.txt_
```
    5: __version__ = '0.6.0'
```

**Comment by mdantonio** [comment]
Some ideas:

in project_configuration we could not use some _magic_ variables? Project_configuration is only managed throuth the controller, so we could be able to configure something like:

```
    9      rapydo:
   10:       branch: __current__
```

To be automatically translated in the current version of controller (since we have this branch synchronization, let's use it)

All templates/*/requirements.txt could not moved from the requirements file directly do the Dockerfile and managed with some input variable?

i.e.:

```
RUN pip install --upgrade git+https://github.com/rapydo/utils.git@0.$CURRENT_BRANCH
RUN pip install --upgrade git+https://github.com/rapydo/http-api.git@$CURRENT_BRANCH
```

by passing CURRENT_BRANCH as build-arg from the rapydo controller:

`docker-compose build --build-arg CURRENT_BRANCH=0.6.0`

**Comment by mdantonio** [comment]
branch: __current__ should be specified in projects_defaults

Doing that we can remove all branch: something from project_configurations

**Comment by mdantonio** [comment]
> by passing CURRENT_BRANCH as build-arg from the rapydo controller:
I'm doing some tests with that.

- removed git+https://github.com/rapydo/utils.git@0.5.7 from requirements.txt
- added RUN pip3 install [...] git+https://github.com/rapydo/utils.git@$RAPYDO_VERSION
- added [ARG RAPYDO_VERSION](https://docs.docker.com/engine/reference/builder/#using-arg-variables)
- added `RUN test -n "$RAPYDO_VERSION"` to make this variable mandatory
- added  `--build-arg $RAPYDO_VERSION=__version__` to the build function (controller.compose.build_images)

As result:

if the variable is missing (should not, since the controller add it) the build fails:

`compose.service.BuildError: (<Service: backend>, 'The command \'/bin/sh -c test -n "$RAPYDO_VERSION"\' returned a non-zero code: 1')`


Otherwise, the build dinamically installs che current version with no need to replace this value on every branch

What do you think? If this is ok, I can fix the other Dockerfiles

Then, I think that this issue can be closed

**Comment by pdonorio** [comment]
This solution is fine with me;

but the only missing point is that also projects have requirements to install the controller, e.g. see [eudat](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.0/projects/b2stage/requirements.txt).

This would be solved with #52, so maybe that one should be finished before closing this one to have it all in the right way?

**Comment by mdantonio** [comment]
That's ok, I can push such modifications on the 0.5.8

**Comment by pdonorio** [comment]
Good, we can tag this in the 0.5.8 branch, 0.5.7 should be delivered today

**Comment by mdantonio** [comment]
Note for myself, once created 0.5.8 branches:

on both controller and build_templates:
```
git stash
git checkout 0.5.8
git stash apply
```

**Comment by mdantonio** [comment]
Found a BUG when using template image not overriden in vanilla.

Since these images are not built from controller (by passing build-args) the start fails because docker compose up build these images without the RAPYDO_VERSION env variable

**Comment by mdantonio** [comment]
The BUG is fixed by the two commits above

**Comment by mdantonio** [comment]
We can close here 
(reopen in case of BUGs or further improvements)
