### ISSUE TITLE
Push template builds on docker hub (with CI)

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#66]
Frontend is still using the very very old image 

[rapydo/frontend](https://hub.docker.com/r/rapydo/frontend/)

We should at least add this build to the templates

The optimum would also be to update it

**Comment by mdantonio** [comment]
The same is required for bower

[pdonorio/jsdev](https://hub.docker.com/r/pdonorio/jsdev/)

**Comment by pdonorio** [comment]
How to use travis to push builded images:
https://sebest.github.io/post/using-travis-ci-to-build-docker-images/

**Comment by pdonorio** [comment]
To be pushed in https://hub.docker.com/u/rapydo/dashboard/

**Comment by pdonorio** [comment]
- [ ] create/update frontend image
- [ ] create/update bower/nodejs image
- [ ] create one rapydo/REPO for each needed image in build
- [ ] add pushing images to hub repositories

**Comment by pdonorio** [comment]
> Frontend is still using the very very old image

About this one we should decide if we want to keep using `gevent` or another WSGI.
Also we should write a list of requirements based on what really is needed frontend side, which should be few packages.

**Comment by pdonorio** [comment]
> The same is required for bower

For nodejs it looks like the official image (latest version is already at 8) can be found as alpine flavour: `8.5.0-alpine`

src: https://hub.docker.com/_/node/

**Comment by mdantonio** [comment]
With the new frontend build, we should try yo upgrade the code to remove the common folder and use rapydo utils instead

**Comment by mdantonio** [comment]
https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84

The use of -cache-from sounds as an intestresting thing... but it is not supported by docker-compose (only by docker)

By mixing images on docker hub and local builds we could obtain something like this?

`docker build --cache-from rapydo/backend:0.5.6 --file blabla/backend/Dockerfile --tag rapydo/backend:0.5.7`

=> a faster build of 0.5.7 because starting from released 0.5.6?

Could be very usefull also for unittests (very slow now)

But if it is only supported by docker, how could we use that?

**Comment by mdantonio** [comment]
pdonorio/jsdev is no longer required

rapydo/frontend is updated with a new build based on nodejs (see #90 for details)

I keep this issue open to allow the ingration of travis to automatically create images (to be used in production) from builds

**Comment by pdonorio** [comment]
> add pushing images to hub repositories from travis

I never did this, we should check how to do it

**Comment by pdonorio** [comment]
This is important to be able to go to production faster (or to deploy automatically to production also)

**Comment by mdantonio** [comment]
This could be also very useful to hugely speed up unittests on http-api, utils and do, since at the moment a large parte of time is spent do build the image

**Comment by mdantonio** [comment]
Here some hints on how to deploy from travis to docker hub:

https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by mdantonio** [comment]
Added a new command: `rapydo pull` to pull base images from docker images

Since any rapydo command (included rapydo pull) requires the project to be initialized and since rapydo init is also responsible to check and build template images, I added a new option `rapydo init --no-build` to skip checks on build templates

Now it is possible to speed up the deployment with the following combination of commands:

`# Init the project but do not touch docker builds`
`rapydo init --no-build`

`# Pull base images from docker hub`
`rapydo pull`

Optional:
`# Verify base templates, in case of missing images on docker hub`
`rapydo init`

I applied these commands to both controller and http-api unittests resulting in a good saving of time, e.g.

Before:  `PROJECT=irodstest  8 min 15 sec`

After: `PROJECT=irodstest   3 min 26 sec`

All good... but this problem remains:


> during the build we create the developer user by passing the CURRENT_UID as build-arg. All pushed images will be created with the uid of the travis environment, not the uid of the user running the stack on the host machine

**Comment by mdantonio** [comment]
An option to overcome this issue is to add a preliminary step to docker-entrypoints to verify the UID and change it if required:

`usermod -u ${CURRENT_ID} developer`

**Comment by mdantonio** [comment]
But the problem is that usermod cannot be used to change uid if the user is already logged in (we have to execute it as another user, i.e. root)

**Comment by mdantonio** [comment]
Since the docker entrypoint is launched as root (and then commands are then executed with sudo) to fix a simpler than expected

By adding this to the docker entry point we are able to fix the user if wrong:

```
DEVID=`id -u developer`
if [ "$DEVID" != "$CURRENT_UID" ]; then
    echo "Fixing developer uid from $DEVID to $CURRENT_UID..."
    usermod -u $CURRENT_UID developer
fi
```

The problem is that this fix is not persistent and has to be executed at every execution... but since it is very quick it should not be a problem...

@pdonorio what to do you think about it?

I can add this piece of code to every image creating custom developer users (backend, backendirods, icat, restclient)

**Comment by pdonorio** [comment]
Uhm 🤔 
I'm ok for now with this in every execution.

But what do we need to make it persistent instead?
Adding /etc to a volume?

**Comment by mdantonio** [comment]
It works, from my side that's all

Do some tests, then you can close

**Comment by pdonorio** [comment]
ok, thanks.

So possible better feature: `/etc` as a volume, but I hope to find a better solution to be honest.
