### ISSUE TITLE
packaging do

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#7]
Depends on #2

**Comment by pdonorio** [comment]
A possibility is to add instructions to use packaging with docker and virtualenv.

**Comment by pdonorio** [comment]
Still do not know how to solve the ABSOLUTE_PATH problem :/

**Comment by pdonorio** [comment]
We should allow the execution of `do` inside a cloned rapydo core for testing.

**Comment by mdantonio** [comment]
> We should allow the execution of do inside a cloned rapydo core for testing.

It is done by supporting a --development flag. This switch disables some checks, e.g. upstream verification and the requirement for project_configuration edit

**Comment by pdonorio** [comment]
Testing on Pypi development version:

https://testpypi.python.org/pypi/rapydo-controller

**Comment by pdonorio** [comment]
Testing the packaging in the [latest](https://github.com/EUDAT-B2STAGE/http-api/blob/0.4.0/.travis.yml) eudat development http-api branch

**Comment by pdonorio** [comment]
All good, I think tomorrow we can release our first alpha in Pypi in production.

**Comment by pdonorio** [comment]
Steps remaining:

- [ ] test eudat removing utils from backend
- [ ] publish utils with correct dependencies
- [ ] publish controller

**Comment by pdonorio** [comment]
> publish utils with correct dependencies

Starting to test with pypi in production:
https://pypi.python.org/pypi/rapydo-utils/

**Comment by pdonorio** [comment]
> publish http-api-base/backend

thoughts on this point:

- backend will not contain configurations (e.g. docker-compose)
- also utils should be downloaded
- backend and utils will be mounted (only in debug.yml) as volumes in 
/usr/local/lib/python3.6/site-packages/
- backend package should provide one or more executables to launch the backend flask server
- 1. exec would be launch flask
- 2. maybe is initialize, or maybe the one above with option?
- 3. clean data?

**Comment by pdonorio** [comment]
There should be in every package a `dev-requirements.txt` for installing when you want to develop, not for adding the library or deploying the package.

**Comment by pdonorio** [comment]
I've published also http-api backend as package, but only in testpypi.
I had to create a `package` branch on each sub repo (http-api, controller, etc.) to avoid madness. 

Now I am debugging what changed with this action:
- all read yaml are missing the log object
- paths have changed, I can fix that with the rapydo.utils.helpers
- others to see

**Comment by pdonorio** [comment]
Files that should be moved from backend into rapydo/core as well:

```bash
./backend/rapydo/confs/services.yaml
./backend/rapydo/models/swagger.yaml
./backend/rapydo/swagger/*
```

Applying a work around for now

**Comment by pdonorio** [comment]
> flask_ext should be moved inside rapydo

warning: I did this :D

**Comment by pdonorio** [comment]
Things missing we must complete tomorrow together:

> write correct requirements for each repo

- [ ] we should work out the right one for backend

> Files that should be moved from backend into rapydo/core

- [ ] what should we do here and most of all with the swagger dir?

> things I broke

- [ ] I removed git checks on controller because of switching repos to branch != master
- [ ] run and manage now exists on both backend and rapydo core, fix this
- [ ] others I don't remember now

**Comment by pdonorio** [comment]
https://pypi.python.org/pypi/rapydo-http/0.1
