### ISSUE TITLE
Check permissions

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#70]
We should verify if folders and files are owned by the right users

For example when the bower lib is owned by root (i.e. after a mount of a non-existing folder) bower fails to install libs

**Comment by pdonorio** [comment]
I already created a similar function for checking folder/files permissions on certificates. Just for the record, it's [here](https://github.com/rapydo/utils/blob/master/utilities/certificates.py#L250-L278)

**Comment by mdantonio** [comment]
Implemented a recursive check on files and folders to verify file permissions:

- if path is readable
- if path is writable
- if path is owned by the current os user

In case of errors now a warning is raised, to be verified if this is enough

Maybe some paths *must* be owned by different users (for example certificate folder), in this case we can skip this kind of special paths

If this check is too slow, we can add an option to skip it when not wanted

**Comment by pdonorio** [comment]
I think this was quite tested, I do receive warnings when permissions are not correct. Should we close?

**Comment by mdantonio** [comment]
Ok
