### ISSUE TITLE
Swagger validation

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#72]
See [the old eudat issue](https://github.com/EUDAT-B2STAGE/http-api/issues/58) about the problem of validating data in input/output as specified by the current swagger JSON.

**Comment by pdonorio** [comment]
This is highest priority for me 💯 

Wwagger validation thanks to `bravado` python library from Yelp is possible:
- [Validate json models with swagger and bravado – Mark Betz – Medium](http://j.mp/2MYUr1B)
- https://github.com/Markbnj/json-validation/blob/master/mycars_app.py#L40-L47
- [json-validation/validator.py at master · Markbnj/json-validation · GitHub](https://github.com/Markbnj/json-validation/blob/master/validator.py#L4-L9)

**Comment by pdonorio** [comment]
Notes:
```
- backend INPUT validation from parameters in swagger
  + names
  + type
- backend OUTPUT follows a swagger example/model?
- frontend forms validation follows other schemas?
```

**Comment by pdonorio** [comment]
This is still important for the framework on long term, but not personally for me.

@mdantonio you can close if you are not going to look into it soon, we can always look into it in the future.

**Comment by mdantonio** [comment]
I will not work on this issue in the near future, but since it is a very important issue don't close it

**Comment by mdantonio** [comment]
Swagger validation is now implemented by using bravado.
More enhancements are not planned, since next versions will gradually remove the swagger definitions as backend configuration input
