### ISSUE TITLE
Is the __main__.py in projects really required?

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#74]
We have a __main__.py copied into each project:

`projects/$VANILLA_PROJECT/backend/__main__.py`

These files are also equals to

`submodules/http-api/restapi/__main__.py`

Could we use the restapi main and avoid to copy? (off course we may create a link, but I don't like links, if you can avoid it)

**Comment by pdonorio** [comment]
will look into this now

**Comment by pdonorio** [comment]
I can't see a simple solution here. There must be a main somewhere, and due to the fact that projects are not packages (unlike `restapi`) we need to put the main in the directory where python is running the code.

The only possible alternative would be a smaller __main__.py which would do something like:

```python
from restapi.__main__ import app

if __name__ == "__main__":
    app.run(host='0.0.0.0', threaded=True)
```

**Comment by mdantonio** [comment]
We cannot put this __main__.py in the backend build?

**Comment by pdonorio** [comment]
Uhm. Maybe we can use directly the path from the python lib in docker for the flask app setting:

```bash
developer@rapydo_server:/code$ env | grep FL
FLASK_APP=/usr/local/lib/python3.6/dist-packages/restapi/__main__.py
FLASK_CMD=restapi launch
FLASK_DEBUG=1
FLASK_PORT=5000
```

Ok, the above setup works if I delete the main for the project.

What does not work is the setup for uwsgi in production:
```bash
[...]
added /usr/local/lib/python3.6/dist-packages/ to pythonpath.
# I have changed UWSGI_APP=restapi/__main__.py but:
ModuleNotFoundError: No module named 'restapi/__main__'
[...]
```

Maybe digging more we can solve it by simple changes to parameters.

**Comment by mdantonio** [comment]
uwsgi does not work because it require a module (now is $VANILLA.__main__) and not a path (as for FLASK, configured as $VANILLA/__main__.py)

We cannot set /usr/local/lib/python3.6/dist-packages/restapi/__main__.py because this is a path neither 
usr.local.lib.python3.6.dist-packages.restapi.__main__ because this is an invalid module

How to solve this problem? I found no option in uswgi configuration

I back to my previous question:

We cannot put this __main__.py in the backend build?

We can 
- put `__main__.py` in backend build (and in celery build too)
- add main in Dockerfile `COPY __main__.py /code/`
- configure  FLASK_APP: ${PYTHON_MAIN_FILE}.py
- configure  UWSGI_APP: ${PYTHON_MAIN_FILE}

What do you think?

**Comment by pdonorio** [comment]
> We cannot set /usr/local/lib/python3.6/dist-packages/restapi/main.py because this is a path neither
usr.local.lib.python3.6.dist-packages.restapi.main because this is an invalid module

This is why we add [these python path](https://github.com/rapydo/build-templates/blob/master/backend/uwsgi.ini#L32-L33) to uwsgi.
So then uwsgi should see `restapi.__main__`.

The question is why that does not work.

**Comment by pdonorio** [comment]
The problem was that UWSGI_APP needs to be `restapi.__main__`, it works

**Comment by pdonorio** [comment]
We need to change the `core` in:

```yaml
FLASK_APP: restapi/${PYTHON_MAIN_FILE}.py
UWSGI_APP: restapi.${PYTHON_MAIN_FILE}
```

**Comment by mdantonio** [comment]
> We need to change the core in:

Changed core -> confs/backend.yaml

With a little change, FLASK_APP is expected to be an absolute path. Working configuration is:

```
FLASK_APP: ${PYTHON_PATH}/restapi/${PYTHON_MAIN_FILE}.py
UWSGI_APP: restapi.${PYTHON_MAIN_FILE}
```

**Comment by mdantonio** [comment]
Now controller verifies if project/$VANILLA/backend/__main__.py exists

If exists it raises an error:

`2017-11-30 10:07:56,223 [EXIT    controller.app:276] Project neo contains an obsolete file or folder: projects/neo/backend/__main__.py`


To fix this error you have to delete the reported file

**Comment by mdantonio** [comment]
Tested on rapydo core on both debug and production mode.

I close the issue, if required reopen
