### ISSUE TITLE
The squashed commit hell

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#75]
Since we now merge squashing commits, the develop tool should switch to master and pull it before creating the new branch.

**Comment by mdantonio** [comment]
I created the 0.5.7 branch by hand from master, so we have a use case to test it before the implementation on develop

**Comment by pdonorio** [comment]
I've created the pull requests for `0.5.7` to check and close this issue.

**Comment by pdonorio** [comment]
Confirmed that starting from master hell remains under the ground
