### ISSUE TITLE
Change name of template images

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#76]
Now for every vanilla project we create template images with the following naming convention:

`$VANILLA/service:template
`
But in this way, when we work on several projects, we produce a lot of template images.

For example i currently have 8 backend templates on my pc and at every new version I have to rebuild a lot of images

Changing the naming convention in something like this:

`rapydo/service:VERSION`

we could reduce the number of built images and avoid unnecessary re-build

Note: this way we have to change the FROM image in our vanilla builds at every new version. This is cumbersome but also more explicit and more correct: now we have vanilla branches fixed to a specific version (thanks to project_configuration) but with builds referring to the "latest" template: this is wrong!

**Comment by pdonorio** [comment]
Note to self that came to mind: docker images are based on commit hashes. The same image with two different names does not occupy more space of the disk

**Comment by mdantonio** [comment]
You are right, but only if every image is built on the basis of the same Dockerfile. If I change the Dockerfile and only re-build one of those images (e.g. the project on which I work daily and not the one on which I work not so often) I will keep two different images

For example all those images should be no more than a couple (rapydo:0.5.7 and rapydo:0.5.6):

```
$ docker images | grep backend | grep template
nig/backend                   template            d8742309290b        20 hours ago        646MB
celerytest/backend            template            39cd077c83e2        26 hours ago        647MB
imc/backend                   template            a6203aee77f3        3 days ago          646MB
baserepo/backend              template            3abc895bd271        12 days ago         646MB
b2stage/backend               template            427395da749a        2 weeks ago         646MB
basic/backend                 template            2ba430651bf7        4 weeks ago         646MB
neo/backend                   template            2ba430651bf7        4 weeks ago         646MB
sql/backend                   template            2ba430651bf7        4 weeks ago         646MB
```

But based on hashes I have 6 images.
imc/backend is a 0.5.6, all others are 0.5.7

When I will back to work on, just as example, baserepo I will be forced to rebuilt the template to be updated (and obtain the same hash already available for nig/backend)

Note: based on what implemented in #65 with env variables passed to Dockerfile via docker-compose build maybe we could set something like this:

```
env RAPYDO_VERSION
FROM rapydo/backend:$RAPYDO_VERSION
```

To avoid having to change this each time

**Comment by mdantonio** [comment]
By naming template build as "rapydo/$service" we can obtain a name collision with the images produced in #66 

At the moment I don't know if this is a good or a bad thing

Could be a good thing? By changing nothing in the configuration, only disabling building from rapydo-controller (based on --mode production or by allowing a specific flag) che could obtain ad easy swith between builds and images

Or could be a bad thing and create lots of problems?

**Comment by mdantonio** [comment]
Note: to implement this change we have to:

- modify confs/backend (where build name are decided)
- modify controller at builds:76 (where FROM images are verified from vanilla builds)
- modify vanilla builds (rapydo:celerytest; telethon; imc)
- modify test_and_coverage (template/backend:template is used as base image for coveralls, to be replaced with rapydo/backend:$VERSION)

**Comment by pdonorio** [comment]
> Or could be a bad thing and create lots of problems?

we don't know, but we may check

**Comment by mdantonio** [comment]
here everything should be completed

I tested with a couple of projects, to test further

**Comment by pdonorio** [comment]
It works for EUDAT too now
