### ISSUE TITLE
Neo4j web shell: enable https in production

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#77]

**Comment by mdantonio** [comment]
After some tests:

https connection is already enabled by using the official docker image, it is enough to map our 9090 port on 7473 (https) instead of 7474 (http)

in commons add the mapping 7687 on 7687 (bolt)
in debug add the mapping 7474 on 9090 (http)
in production add the mapping 7473 on 9090 (https)

Then, we have to configure the ssl certificate

We can use letsencrypt by mounting letsencrypt_certs volume on /ssl

Neo4j expects to find `/ssl/neoj4.cert` and `/ssl/neo4j.key`

but we have:

`/ssl/real/fulchain1.pem` and `/ssl/real/privkey1.pem`

A simple symbolic link should be enough as described here:

https://serverfault.com/questions/809413/use-letsencrypt-certs-with-neo4j

It seems ok and the web interface loads with the green locker, but the connection to bolt fails with the following error:

`N/A: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3`

The last sentence maybe the point: If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use.

I tried to follow this:

https://stackoverflow.com/questions/31664366/chrome-failing-to-connect-to-websocket-server-opcode-1-handshake-was-cancele

But with no success

It works on firefox, not on chrome&opera

**Comment by mdantonio** [comment]
Found a working solution (to be refined by testing it on more computer/OS): 

- export the certificate from the browser (in p7b format... to be verified if also other formats are ok)
- open the server URI on bolt port via https (https://URL:7687)
- add the certificate as trusted certificate (directly on the OS?)

**Comment by mdantonio** [comment]
A second option to be investigated is to put neo4j behind nginx

https://stackoverflow.com/questions/45990168/neo4j-with-a-reverse-proxy-and-nginx

**Comment by pdonorio** [comment]
In my last certificate update I've found:

```
rm: can't remove 'neo4j.cert': No such file or directory
rm: can't remove 'neo4j.key': No such file or directory
```

**Comment by mdantonio** [comment]
added a -f flag to avoid such errors
