### ISSUE TITLE
rapydo template

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#81]
- [x] Unittest produced by rapydo template are based on nose2 => to be fixed to use pytest
- [ ] As plus: we could extend rapydo template to also produce frontend stuffs

**Comment by pdonorio** [comment]
We must switch the template from nose2 to pytest

**Comment by pdonorio** [comment]
@mdantonio still interested in using it for frontend?
In that case shouldn't we have another command (and issue) maybe? e.g. `rapydo webpage newname` that creates: 
- HTML base
- js component scaffold
- unittest template

**Comment by mdantonio** [comment]
> still interested in using it for frontend?

Definitely not
