### ISSUE TITLE
Check development mode before starting

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#82]
If I do:
```bash
rapydo --development init
rapydo --development start
```

while:
```bash
rapydo init
rapydo --development start
```

The second one fails, not founding the folders in submodules.

--

Also note that `GitPython` does not work at the moment with `git` >= `2.15` (see [issue](https://github.com/gitpython-developers/GitPython/issues/687))

**Comment by mdantonio** [comment]
This problem is not confirmed by my tests:

Init with development OFF
```
$ rapydo init
... bla bla bla...
```

utils and http-api are not downloaded:

```
$ ls 

ls submodules/
build-templates  _empty  frontend
```

Starting in development mode **DOES NOT WORK**:


```
$ rapydo --development start

2017-11-30 10:23:01,777 [INFO    controller.app:58] Do request: start
2017-11-30 10:23:01,897 [EXIT    controller.gitter:132] Repo https://github.com/rapydo/utils.git missing as ./submodules/utils
```

Please give me more info to reproduce the error... otherwise we can close the issue!

**Comment by pdonorio** [comment]
Re-tested today against a freshly installed B2STAGE 1.0.1 and no issue found.

**Comment by pdonorio** [comment]
The gitpython issue was fixed by the author so we removed the check.
