### ISSUE TITLE
Admin email

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#83]
To use SMTP ( #36 ) you have to configure a SMTP_ADMIN address, now configured at vanilla level:

projects/$VANILLA_PROJECT/conf/common.yaml:

`SMTP_ADMIN: ${SMTP_ADMIN}`

project_configureation.yaml:
`SMTP_ADMIN: xyz@abc.com`

We could use the same variable to configure let's encrypt certificate request, to be notified when the certification is near to expire by adding the variable to nginx container and a default (empty string?) in projects_defaults

**Comment by pdonorio** [comment]
We can test the maintainer email in my next production test next week

**Comment by mdantonio** [comment]
> We can test the maintainer email in my next production test next week

@pdonorio did you test it?

**Comment by pdonorio** [comment]
Will do

**Comment by pdonorio** [comment]
First time:

```
touch: /root/.acme.sh/account.conf: No such file or directory
grep: /root/.acme.sh/account.conf: No such file or directory
grep: /root/.acme.sh/account.conf: No such file or directory
./acme.sh: line 1884: /root/.acme.sh/account.conf: No such file or directory
grep: /root/.acme.sh/account.conf: No such file or directory
touch: /root/.acme.sh/http.header: No such file or directory
[Fri Mar 16 14:18:36 UTC 2018] Registering account
[Fri Mar 16 14:18:37 UTC 2018] Registered
[Fri Mar 16 14:18:37 UTC 2018] ACCOUNT_THUMBPRINT='cf9B193A2P9vjYDKxTWpEPYsEd0KZHsmA-MkcIveMEg'
Email account updated
```

Second:
```
Reference email: p.don****
[Fri Mar 16 14:19:40 UTC 2018] Registering account
[Fri Mar 16 14:19:42 UTC 2018] Already registered
[Fri Mar 16 14:19:42 UTC 2018] ACCOUNT_THUMBPRINT='cf9B193A2P9vjYDKxTWpEPYsEd0KZHsmA-MkcIveMEg'
Email account updated
```

Did it work? I don't know. I didn't receive any email, I guess we will have to wait for three months? :)

**Comment by pdonorio** [comment]
Still two months left...

**Comment by pdonorio** [comment]
So no luck, I set the CINECA email I don't have anymore.
@mdantonio did you ever test this? Should we close anyway?

**Comment by mdantonio** [comment]
Never received any email from letsencrypt. But i think that i'm not passing the SMTP_ADMIN variable to proxy... 

I change my configuration (it is enough to SMTP_ADMIN in proxy env?) so that i will be able to test in the future

**Comment by pdonorio** [comment]
Let's wait for it

**Comment by pdonorio** [comment]
Worked for both
