### ISSUE TITLE
Support of old versions

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#89]
Today i tried to build backend:0.5.7 and found many many problems

0.5.7 is not an old version (it was che stable version until a week ago!), I do not want to imagine what may happens with older versions

Just few examples:

- the build was based on ubuntu 17.04 (now unsupported)
- backend was requiring python-irodsclient version 0.7.0a0 (this version no longer exists)
- backend was requiring rapydo-utils (just after the release of 0.6.0 this means the installation of utilities 0.6.0 on http-api 0.5.7)

More in general we known that a specific version works when we release it, buy we need something to be sure that a certain version (that we want to support) continues to work: for example we should periodically run travis tests

If tests continue to pass we know that a certain version still works and we can support it

When a test no longer pass we can decide if fix the version (i.e. with 0.5.7) or to deprecate the version (i.e. with 0.5.5)

The problem can be easily fixed? Do it and continue to support the version

The problem is not trivial but the version is still very very recent? Try to fix the problem and continue to support the version

The version is no longer recent and the problem is not trivial? Deprecate that version!

To be discussed what a deprecated version means

Let user to install it but with no support nor guarantees?
Or disable pip package and github branch to avoid users to use it?

**Comment by mdantonio** [comment]
We can create a wiki page to report deprecated versions (may we use it also as centralized changelog?)

**Comment by pdonorio** [comment]
Wiki and changelog to be issued inside the `issues` repo?

**Comment by mdantonio** [comment]
Just listed rapydo versions here: https://github.com/rapydo/issues/blob/master/README.md

Tried to add a changelog, but a compact changelog to be inserted there is too much difficult to be achieved (in particular for older versions)
