### ISSUE TITLE
Cluster mode

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#9]
Compare as soon as possible the use of docker swarm mode with docker.py versus how we use the internal python code of docker-compose.

**Comment by pdonorio** [comment]
A reference here is mdantonio/rapydo#2

**Comment by pdonorio** [comment]
This issue is still important but oriented towards our recent (ab)use of `rancher`:

- [ ]  integrate `rancher` API in the `controller` like [so](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.3/projects/b2stage/backend/apis/services/rancher.py#L22) and used then [here](https://github.com/EUDAT-B2STAGE/http-api/blob/1.0.3/projects/b2stage/backend/apis/commons/cluster.py#L38-L45)
- [ ] convert the sum of the YAML configuration into a single file to use `rancher compose` in deploying services on a cluster

**Comment by pdonorio** [comment]
uh oh! https://testdriven.io/running-flask-on-docker-swarm#objectives

**Comment by pdonorio** [comment]
Bump to my self on this

**Comment by pdonorio** [comment]
Is this still interesting for you @mdantonio ?

**Comment by mdantonio** [comment]
From a general point of view: yes, a support for any kind of clustered deployment would be very useful.

At the moment we have two use cases requiring the deployment on 2+ hosts and we indepentenly manage the different machines, but this often brings to version misalignments and waste of time.

Another nasty problem is that now we have to create different stacks (modes) very every machine in every environment.
Just as example: a deployment with environments  including a PROD instance (with 3 VMs), a TEST instance (with 2 VMs) and a DEV instance  (with a single VM) and three main components:

We need a dev mode with all three components togheter

Then we ned test1 mode with the component deployed on VM1 e test2 mode with the two components deployed on VM2

Then we need prod1, prod2 and prod3 modes each with the single component deployed on the prod VM

6 different combination of services, each specific for the different VMs

That's a bit crazy and may be greatly simplified by adopting a clustering support and obtain something like that:

```
rapydo --mode production --hosts DEV start 
rapydo --mode production --hosts TEST1,TEST2 start 
rapydo --mode production --hosts PROD1,PROD2,PROD3 start 
```

But how to reach that from a practical point view? Swarm, Rancher, Kubernetes ... all these options are quite far to be integrated (Kubernetes is for sure most complicated... but also the most interesting)

**Comment by pdonorio** [comment]
If you have in mind a dedicated configuration for each host of your test/dev/prod environment, docker machine might be enough for you.
You just switch machine and rapydo start that conf on that host.

Swarm is the only simple option to use the same docker compose you already have, but it's becoming kinda deprecated because of Kubernetes.

Kubernetes on the other hand is much more complicated and requires a specific format/conversion from docker compose, losing the single language for describing your containers.
Rancher 2 is just a wrapper for kubernetes, I don't think it's a dedicated option anymore.

The situation is not ideal.

**Comment by mdantonio** [comment]
> If you have in mind a dedicated configuration for each host of your test/dev/prod environment
Of course I would not, this is a similar configuration than now... and his is a very very confusing/time-wasting/error-prone approach

> to go with kubernetes, which seems the only way forward (good luck for the effort), the shortest path remains https://kompose.io/getting-started

Very few changed in the last couple of years and the landscape remained the same.

I'm waiting for a use case really requiring that, to use as a driver and to start working on it

**Comment by pdonorio** [comment]
I've been listening to [this podcast](https://podcasts.google.com/?feed=aHR0cHM6Ly9mZWVkcy50cmFuc2lzdG9yLmZtL2Rldm9wcy1hbmQtZG9ja2VyLXRhbGs&episode=MzYyZmFjYmItNDkwYS00NjRiLWI3NTAtNGMwNjVkMTUyZDM4)

So it seems Rancher has released this [k3s](https://k3s.io/), which in their view is the tool trying to make Kubernetes work as simply as Swarm does.
There's also a [k3os](https://k3os.io/) to simplify the use of k3s - like they used to do with rancheros - and a [k3d](https://github.com/rancher/k3d) to use k3s with docker for mac and windows.

As far as they say, you should be able to use k3s as your Kubernetes development working copy on your local machine. 
So for clusterized versions of rapydo you would have k3s (or equivalent or Kubernetes) on your machine and then run some Kubernetes orchestration commands based on its own YAML format.

---

A reflection at the end of this is if we will ever need to go for a too complex task in orchestration in rapydo. 
If that's the case, and I think it is, Docker Swarm is still the suggested mode (listen to [this other podcast](https://podcasts.google.com/?feed=aHR0cHM6Ly9mZWVkcy50cmFuc2lzdG9yLmZtL2Rldm9wcy1hbmQtZG9ja2VyLXRhbGs%3D&episode=YzFlZWFmMWUtZDA2YS00ZTgzLWExMWYtMDlmZmFlY2UzOWU0) from the same series about it).

It would keep almost all the compose YAML we have.

Finally, from the same podcasts I've also found out about [compose-on-kubernetes](https://github.com/docker/compose-on-kubernetes#compose-on-kubernetes) which would allow something like:
```bash
docker stack deploy --orchestrator=kubernetes -c docker-compose.yml SOME_SERVICE
```
When did that happen 😓

**Comment by mdantonio** [comment]
swarm introduced in v2.0
