### ISSUE TITLE
Porting to node.js + Angular

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#90]
We started the migration from Angularjs (version 1.5.5) to Angular (version 5)

Before that we have to migrate from Flask to node.js

I'm working on a compatibility version (0.6.1) to allow to start both old (flask+angularjs projects) and new (node.js + angular5 projects)

Some key point already implemented:

- branch master on frontend remains stuck on flask + angularjs

- branch 0.6.1 on frontend is upgraded to node.js + angular5

- rapydo-confs/projects_defaults is still configured to use master frontend

- vanilla projects can specify to use branch 0.6.1 and start the frontend migration

- rapydo-confs / frontend.yml is still based on flask configuration

- rapydo-confs / frontend-a2.yml is the new frontend compose file with node.js

- rapydo-controller 0.6.1 temporary verify if selected frontend branch is master or not. If you selected a different branch (0.6.1) it automatically switch from frontend.yml to frontend-a2.yml

- in rapydo-templates I added a frontend build (not used in old configuration)

- with new configuration rapydo/frontend is no longer used

- with new configuration bower is no longer used => pdonorio/jsdev is no longer used

**Comment by mdantonio** [comment]
I obtained a fairly working configuration (development mode + only common code) with node.js and angularjs

next steps:

- add angular5 + typescript code
- include vanilla code
- production mode

I'm following this upgrade documentation:

https://angular.io/guide/upgrade

P.S. we have to introduce a module loader to start working with angular5. Old angular official guides were based on SystemJS but since angular CLI is now based on webpack this is a standard choice

Today i did some experiments with SystemJS ... tomorrow i will try angular CLI and webpack to go deeper with the integration

**Comment by mdantonio** [comment]
Some updates:

> next steps:
> add angular5 + typescript code
> include vanilla code

Both done


> production mode
We already have a build configuration to work in production (the build fails for some weird problem, but we will face this problem later). Once created our dist we have to server it with an nginx server


> I'm following this upgrade documentation:
> https://angular.io/guide/upgrade

Added ngUpgrade and make the hybrid app working (first we bootstrap Angular app, then from angular we bootstrap AngularJS app=

> P.S. we have to introduce a module loader to start working with angular5. Old angular official guides were based on SystemJS but since angular CLI is now based on webpack this is a standard choice

Now we are on webpack

Next steps:

- [ ] Fix npm run build (SourceMap error)
- [ ] Add nginx to server production server
- [ ] Introduce Angular routing (try to follow this approach http://www.syntaxsuccess.com/viewarticle/ngupgrade-with-the-angular-router-and-ui-router)
- [ ] Try the porting of some component (maybe login?)

**Comment by mdantonio** [comment]
> Fix npm run build (SourceMap error)

It is done. The problem was hotkeys. Since we are not really using this library I removed it instead of try to fix.

> Introduce Angular routing

Done... with a bug: after a transaction from Angular context to AngularJS we are unable to clear the router-outlet. The opposite side works fine (we are able to clean the ui-view div)

I also successfully injected the rootScope into the Angular app, but with a bug: if the component is access as entry point (for example by directly pointing the url on it) it raises an error because the angularjs is still starting but the angular app is already trying to inject the rootScope (not yet created)

**Comment by mdantonio** [comment]
Next steps:

- [ ] Add nginx to server production server
- [ ] Try the porting of some component (maybe login?)
- [ ] Fix rootScope bug
- [ ] Fix router-outlet cleanup

**Comment by mdantonio** [comment]
> Add nginx to server production server

Done, but angularjs fails to start with the following error:

```
Failed to instantiate module $$UpgradeModule due to:
Error: [$injector:modulerr] Failed to instantiate module web due to:
Error: [$injector:unpr] Unknown provider: e
```

I don't known what this provider 'e' should be... maybe it is an uglified name?

**Comment by pdonorio** [comment]
More tutorials that could have some good info for starting:

- https://www.toptal.com/angular/angular-5-tutorial
- https://medium.com/@amcdnl/angular-component-design-anti-patterns-14ed34c538a7
- https://www.codementor.io/antonihuguetvives/building-pwas-with-angular-5-gerfaz88x

**Comment by mdantonio** [comment]
Fixed the injection error in production mode

To solve the problem I enabled the strictID flag to block non explicitly annotated providers

That I fixed all providers by adding explicit annotation:

https://docs.angularjs.org/error/$injector/strictdi

i.e.

```
function blabla($a, $b, $c) {
    [...]
};
blabla.$inject = ["$a", "$b", "$c"];
```

When the code is minified non explicit annotations can produce errors and due to minification is not possibile to debug the problem => always enable strictID to ensure compatibility in production mode

**Comment by mdantonio** [comment]
>  also successfully injected the rootScope into the Angular app, but with a bug: if the component is access as entry point (for example by directly pointing the url on it) it raises an error because the angularjs is still starting but the angular app is already trying to inject the rootScope (not yet created)

Found a working pattern:

Component implements OnInit

constructor injects private injector: Injector

Injector is imported from @angular/core

ngOnInit injects rootscope as:

`this._rootScope = this.injector.get('$rootScope');`

rootscope is promoted as Provider in app.module

`upgradeAdapter.upgradeNg1Provider('$rootScope')`

**Comment by mdantonio** [comment]
> Try the porting of some components (maybe login?)

re-implemented the login stuffs (implementation quite good.... to be completed, e.g. when tokens expire).
Also downgraded the AuthService to replace satellizer in angularjs

**Comment by mdantonio** [comment]
> Dynamic configuration

Done, replaced the globalConf with a process.env defined with DefinePlugin in Webpack... it works on both angular and angularjs

**Comment by mdantonio** [comment]
Next steps:

- [ ] Fix router-outlet cleanup
- [ ] Fix navbar with mixed links (ng2-router and ui-router)
- [ ] Autocomplete: missing template
- [ ] Remove angular-chips?
- [ ] Logout does not require any confirmation
- [ ] Checks on token expiration

**Comment by mdantonio** [comment]
>Autocomplete: missing template

Fixed

**Comment by mdantonio** [comment]
>  Fix router-outlet cleanup

and

> Fix navbar with mixed links (ng2-router and ui-router)

Both fixed

**Comment by mdantonio** [comment]
Since [ui-bootstrap](https://angular-ui.github.io/bootstrap/) is only compatible with angularjs we have to add something new to use angular over bootstrap

The UI Bootstrap team created [ng-bootstrap](https://ng-bootstrap.github.io/#/home) for Angular2 

ng-bootstrap requires angular5+ and bootstrap4 => we have to upgrade bootstrap from 3.3.7 to 4.0.0

I want to avoid a migration of the whole angularjs code to bootstrap4 (i'm creating such hybrid configuration to avoid migrations!) so we will use both bootstrap3 (for angularjs) and bootstrap 4 (for angular)

npm does not allow to install multiple version of the same library (some tricks allow for it... but do not really work as required)

=> 

We install bootstrap4 with npm and bootstrap3 by hand (in docker-entrypoint)

Everything seems to work and now we have:

angularjs 1.5.5 + bootstrap 3.3.7 + ui-bootstrap 2.5.6
and
angular 5.2.3 + bootstrap 4.0.0 + ng-bootstrap 1.0.0

running together

**Comment by pdonorio** [comment]
Can we close?

**Comment by mdantonio** [comment]
We are still working on it, although without updates here

However we can close since I do not think we'll update this issue
