### ISSUE TITLE
Mapping the host user to containers main users

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#94]
`rapydo` knows the `UID` of the current owner of the docker images/containers.

We should map it at build time to the main `UID`s of the containers:
- backend
- celery
- icat

We can use an `ARG` in the `Dockerfile`.

**Comment by mdantonio** [comment]
It is done, just waiting the completion of unit tests ... then @pdonorio you will be able to make some tests

**Comment by mdantonio** [comment]
Unit tests successfully completed

**Comment by pdonorio** [comment]
Testing on my side

**Comment by pdonorio** [comment]
Tests completed we can close
