### ISSUE TITLE
A python standalone template-based configurator for docker images

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#95]
We could create a standalone python script with `jinja2` by using something like this:

http://www.pyinstaller.org

Then we can adopt such script here for any docker build requiring dynamic configurations.

**Comment by pdonorio** [comment]
Workaround for a template to be replaced with env variables on nginx:
https://matthiasnoback.nl/2018/03/defining-multiple-similar-services-with-docker-compose

**Comment by pdonorio** [comment]
This is interesting but probably to be investigated after the summer

**Comment by mdantonio** [comment]
I really think that no one will ever work on this. I will reopen if some new use case will require this kind of feature
